### ISSUE TITLE
Improve full-text searching by expanding reference primary

### ISSUE THREAD

**Issue by prowns** [project-lux/lux-marklogic#100]
**Problem Description:**
All records (YPM, AAT, Wikidata, GBIF) have the same primary name: Equus Caballus.  Most users would search "horse".   The issue is raised by art museums, who use Horse as subject heading, and include this in their data under "represents".  Discussion surfaced an inconsistency in how simple search is working.

Question: how is simple search working?  It is not consistent for this use case. 

- _boxley horse_ retrieves the [right records](https://lux.collections.yale.edu/view/results/works/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22boxley%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22horse%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=boxley+horse)
- _boxley sheep_ does NOT retrieve the right record ([this one](https://lux.collections.yale.edu/view/visual/b50fb93f-dc1d-4e49-a3b8-acc1cfd4a174)) but it should as Ovis is listed in Depicts. 

**Expected Behavior/Solution:**
Simple search should work such that _boxley sheep_ would retrieve the correct record, even though the primary name is _Ovis_.   

Change simple search to use `referenceName` instead of `referencePrimaryName`

Make the same change for the **Name** field in Advanced Search

**Requirements:**
- New Simple Search index name will be `referencePrimaryName`
- Advanced Search name field will use the extended index in Simple Search (referencePrimaryName) 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] ~Wireframe/Mockup - Mike~
- [x] Committee discussions - Sarah
- [x] ~Feasibility/Team discussion - Sarah~
- [x] Performance test
- [x] Backend requirements - TBD
- [x] Frontend requirements- TBD
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

The searches below should show this record in the results: https://lux.collections.yale.edu/view/visual/b50fb93f-dc1d-4e49-a3b8-acc1cfd4a174

- [boxley horse](https://lux.collections.yale.edu/view/results/works/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22boxley%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22horse%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=boxley+horse)
- [boxley sheep](https://lux.collections.yale.edu/view/results/works/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22boxley%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22sheep%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=boxley+sheep)

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**

- Additional context in 2/29/24 data wg notes
- Additional context in 4/25 Interactions notes
- https://www.bugherd.com/projects/284041/tasks/2188

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by prowns** [comment]
Horse is a primary name in Equus Caballus, but not labelled as english. This is why it appears, but Ovis does not have this.

**Comment by clarkepeterf** [comment]
Preliminary deployment in DEV looks good. Propose to also do the following:

- change `name` searches to use the `[scope]Name` fields instead of `[scope]PrimaryName`.
- add a new `primaryName` field in each scope which uses `[scope]PrimaryName`

**Comment by prowns** [comment]
Per Interactions 4/25

- New Simple Search name index is great; will continue testing
- Advanced Search
- - Name search should used this extended index as well
- - No need for a separate “primary” name option in Adv. Search

**Comment by prowns** [comment]
Performance test needed before this is deployed.

**Comment by brent-hartwig** [comment]
@clarkepeterf, https://github.com/project-lux/lux-marklogic/issues/11#issuecomment-2033002501 captures related comparisons.

**Comment by prowns** [comment]
Performance tests on 5/9 failed; still determining if issue is with this issue or ML.

**Comment by roamye** [comment]
IT meeting 6/21:
Performance test results are successful. This ticket is no longer blocked and will be deployed in 6/24 cycle.

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in prod! Closing.
