### ISSUE TITLE
Add index properties for Public Domain AS boolean option

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#103]
**Problem Description:**
The issue: https://github.com/project-lux/lux-frontend/issues/47 would like to create a new advanced search Boolean "Are in the Public Doman". This ML issue supports FE47 by looking for a boolean value represented by a 1 or 0 in the indexed properties

**Expected Behavior/Solution:**

 Example | Are in the Public Domain: Yes ([A Noble Lord](https://lux.collections.yale.edu/view/visual/edd6cdf3-bef1-4f61-92e2-ba8d06af9911)):

e.g. the `isPublicDomain` below
```
"indexedProperties": {
"dataType": "VisualItem", 
"uiType": "CollectionWork", 
"isCollectionItem": 0, 
"hasDigitalImage": 0, 
"isOnline": 0, 
"isPublicDomain": 1
}
```

**Requirements:**
- Have ML ticket identify which records are public domain vs are not public domain
- AS in https://github.com/project-lux/lux-frontend/issues/47 will facet correctly to show the script example above for records which have the value of 'Yes' for the Right Status -> Are in Public Domain. 
- AS in https://github.com/project-lux/lux-frontend/issues/47 will facet correctly to show the script example above without the classified_as id for records which have the value of 'No' for the Right Status -> Are in Public Domain. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD
- [x] Frontend requirements- TBD
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- View FE ticket for UAT examples of which records should show when value is yes/no

**Dependencies/Blocks:**
- Blocking: https://github.com/project-lux/lux-frontend/issues/47

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**

- ~These links can consist of resources, bugherds, etc.~

**Wireframe/Mockup:**
~Place wireframe/mockup for the proposed solution at end of ticket.~

**Comment by prowns** [comment]
Added to next Ticket forming - this is blocking an important FE ticket.  @clarkepeterf - what is needed to finish forming this ticket?

**Comment by clarkepeterf** [comment]
@azaroth42 Based on findings from adding `itemHasDigitalImage` in [this ticket from the old repo](https://git.yale.edu/lux-its/marklogic/issues/614) - We need to add a property to the `indexedProperties` section in the data.

If we try to use the data as-is, Works which don't have a `subject_to` field will not appear in the facet (e.g. we could have a 'Yes' for public domain, but we wouldn't have a 'No' for public domain)

If we want to be able to check either 'Yes' or 'No' for being public domain, we need a separate indexed property with a boolean value represented by a `1` or a `0`

**Comment by clarkepeterf** [comment]
@azaroth42 Regarding the comment above, can you confirm if it will be possible to add a `workIsInPublicDomain` field to the `indexedProperties`?

**Comment by clarkepeterf** [comment]
@azaroth42 If a facet is not needed (just advanced search) - it could also be implemented not as a boolean, but as a 'Yes'-matching-only field. (It could still be surrounded by a NOT query) - I suppose that means it could also be turned into a boolean field with some extra tweaking on the frontend

**Comment by azaroth42** [comment]
I can add it to `indexedProperties`. Will make a data-pipeline ticket to block this one.

**Comment by azaroth42** [comment]
https://github.com/project-lux/data-pipeline/issues/65 

I've added `isPublicDomain` on works, default to 0, and then reset to 1 if the CC0 URI is in `subject_to`. Will be in next dataset build.

**Comment by roamye** [comment]
@clarkepeterf once this has been updated please leave a comment.

**Comment by roamye** [comment]
The issue as been re-scoped. @azaroth42 can you please review and verify if this issue is ready for backlog? 

cc: @prowns @jffcamp

**Comment by azaroth42** [comment]
looks good!

**Comment by kamerynB** [comment]
@clarkepeterf Yes, the frontend has multiple ways of adding new lines but it depends on if you want the line break to be at specific spot. If you know where the line break should occur, I believe inserting a `<br />` tag should work when the frontend reads it.

**Comment by prowns** [comment]
@clarkepeterf and @kamerynB - it's ok if this text ends up as a single paragraph as well.

**Comment by clarkepeterf** [comment]
@kamerynB Since it is interpreted from a string `<br /> ` is not processed as HTML, it shows up as a normal string. See [DEV right now](https://lux-front-dev.collections.yale.edu/view/results/works?q=) for an example of including `<br />` in the advanced search config string.I think you'd have to use `dangerouslySetInnerHTML` to allow `<br />` to show up.

**Comment by clarkepeterf** [comment]
@prowns @kamerynB  ok, I guess we don't need the spacing in the paragraph. No worries about `<br />` or newlines

**Comment by clarkepeterf** [comment]
@kamerynB although if you do make it use `dangerouslySetInnerHtml` we could also show a link in the help text, which is what was originally requested

**Comment by kamerynB** [comment]
@clarkepeterf That all sounds good.

**Comment by prowns** [comment]
@roamye  - I'll update the front-end ticket to reflect these changes to the help text.

**Comment by roamye** [comment]
Closing as this ticket was marked as Done the week of 6/3.
