### ISSUE TITLE
Provide convenient means to retrieve a search's generated query (from 621)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#12]
**_If you implement this ticket, you will make Rob very happy!_**

**Problem Description** 
It's a pain to pull from the log, replace `\"` and `\n`, then format.  And it is a common task, either for myself or (to a lesser extent) Rob.

**Expected Behavior/Solution:**
Let's just provide a way to return it via new or existing endpoint.  No need to actually perform the search.

If we end up doing this through the search endpoint, consider doing so for the facets endpoint.  While recently working on them, I added a log statement and had to take similar steps before being able to use it in QC.

Data services have a defined return type.  So rather than plain text, if we use the existing endpoints, we'll have to put the string in a JSON property.

However, a new text-returning endpoint could accept a JSON parameter where each property is a parameter for the specified endpoint.  I'm digging this approach.

**Requirements:**
List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**
- Old ticket: https://git.yale.edu/lux-its/marklogic/issues/621 

**Related links:**

- These links can consist of resources, bugherds, etc.

**Comment by roamye** [comment]
From old tix - 12/14/2023: 

"Per ticket-forming- not a huge level of effort. Next steps- finish prepping." - SP 

@clarkepeterf how can we finish prepping this? Other than formatting it correctly?

**Comment by azaroth42** [comment]
fine to close IMO

**Comment by brent-hartwig** [comment]
:poof:
