### ISSUE TITLE
Only calculate search result scores when necessary

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#123]
**Problem Description:**
Searches that do not require scores are slower than they need to be.  This optimization was identified during the CTS / Optic API comparison effort.  Note that the value of this optimization will likely be fairly low so long as our default sort uses scores --a different topic for discussion.

**Expected Behavior/Solution:**
When scores are not needed, instruct MarkLogic not to calculate them.  At present, scores are only used for two search result sort options.

**Requirements:**
More of a design than requirements:

- Implement the likes of `SortCriteria.areScoresRequired()` and have it return a new member variable's boolean value.  It should be `true` if and only if `SortCriteria._parse` adds at least one one call to `cts.indexOrder` and only adds calls to `cts.indexOrder`.  Note that LUX as a whole only supports sorting by a single criteria while `SortCriteria` supports multiple.  My preference is for `SortCriteria` to continue supporting multiple.
- Update `SearchCriteriaProcessor.getCtsQueryStr()` to add `"score-zero"` an an option into `cts.search()` when `sortCriteria.areScoresRequired()` returns `false`.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] ~Wireframe/Mockup - Mike~
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [x] Backend requirements - see above
- [x] ~Frontend requirements~- none
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- [x] Developer to verify by checking the generated search code.
- [ ] UAT may verify by verifying the search result order is correct for the selected sort option.  From the frontend, one will not be able to tell whether the backend calculated scores

Scenarios to test include:

1. Search without sort criteria, thereby applying the default sort, which is relevance.  Expectation: score-zero option is **not** present.
2. Explicitly request sort by relevance ("Relevance" sort option).  Expectation: score-zero option is **not** present.
3. Randomize the results by score ("Shuffle Results" sort option).  Expectation: score-zero option is **not** present.
4. Search with any of the other sort options.  Expectation: score-zero option **is** present.
5. Search with a combination of the following in the same search request.  Expectation: when the sort parameter includes `random` and/or `relevance`, the score-zero option is **not** present.

**Dependencies/Blocks:**

- Blocked By: None
- Blocking: None

**Related Github Issues:**

None

**Related links:**

None

**Wireframe/Mockup:**

Not needed

**Comment by brent-hartwig** [comment]
Implemented in PR https://github.com/project-lux/lux-marklogic/pull/259 and merged into the release1.22 branch.

**Comment by roamye** [comment]
@brent-hartwig - are these issues deployed to PROD once it has been fixed? or are they only in test and once UAT approval it is deployed to PROD? 

I noticed this ticket and others are not listed in a current milestone so I am unsure if they should be - or if the process is different.

**Comment by brent-hartwig** [comment]
@roamye, per our Teams exchanges I set the milestone on a half dozen tickets.

**Comment by roamye** [comment]
Approved by UAT 8/7

cc: @prowns

**Comment by roamye** [comment]
Closing. Search results look to be sorted fine in PROD.
