### ISSUE TITLE
Add Config for Modules Database

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#124]
**Problem Description:**
There is no JSON config in the repository to create a lux-modules database. This causes errors for new users, they must add a file to the repo or manually create a database.

**Expected Behavior/Solution:**

A `modules-database.json` file exists in the repository under the `src/main/ml-config/base/databases/` directory

**Requirements:**

**Needed for promotion:**
~~If an item on the list is not needed, it should be crossed off but not removed.~~

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

Not for UAT. Testable only by deploying ML locally. Please close to acknowledge completion.

**Dependencies/Blocks:**

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
~~- Blocking: Issues being blocked by the completion of the current issue.~~

**Related Github Issues:**

~~- Issues that contain similar work but are not blocking or being blocked by the current issue.~~

**Related links:**

~~- These links can consist of resources, bugherds, etc.~~

**Wireframe/Mockup:**
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by jffcamp** [comment]
Only reviewable by developers via backend

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
Closing to acknowledge completion.
