### ISSUE TITLE
Scripts to run facets in isolation

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#158]
Related to performance tests, we're looking to capture individual facet request response times for both semantic and non-semantic facets.

**Comment by brent-hartwig** [comment]
Pinging Mr. @clarkepeterf ☝️

**Comment by clarkepeterf** [comment]
@brent-hartwig

1. I'm fine with deleting the script
2. I have not prioritized calculating the difference between sorted and un-sorted semantic facets
3. Agree System monitoring tests could be useful

**Comment by brent-hartwig** [comment]
@clarkepeterf, I deleted this ticket's branch, which only had the one script that we both agreed to delete.  I propose we close this ticket as the other two discussed items are not in this ticket's scope and do not necessarily require their own tickets or follow-up.

**Comment by clarkepeterf** [comment]
Sounds good

**Comment by prowns** [comment]
Per UAT - close
