### ISSUE TITLE
Create RDATA Tenant

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#159]
- Grab tenant code 
  - currently in [this PR](https://github.com/project-lux/lux-marklogic/pull/153)
- Deploy to DEV as separate tenant
- Load RDATA dataset (@azaroth42 where do I find that data?) 
- Redeploy middle-tier
- Redeploy frontend

**Comment by jffcamp** [comment]
@azaroth42, where is the RDATA dataset, for Peter to load?

**Comment by roamye** [comment]
@clarkepeterf is there any missing information needed for this ticket to move from forming -> prioritization review? 

I am moving this ticket to next deployment: 6/24 as it is still in forming.

**Comment by clarkepeterf** [comment]
I will move forward with creating the RDATA tenant before next deployment. I will move to backlog. We will just need to load data to it to make it useful :)

**Comment by jffcamp** [comment]
@azaroth42, we will be creating the rdata tenanent for the 7/8 release. Can you please share the location of the dataset for rdata?

**Comment by roamye** [comment]
@clarkepeterf - is this unreviewable?

**Comment by roamye** [comment]
Approved by UAT 7/22

**Comment by roamye** [comment]
The RDATA tenant: https://lux-front-rdata.collections.yale.edu/ is up and running fine. Closing.
