### ISSUE TITLE
Add ability to influence search result scores by unit responsible for object and works (from 654)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#16]
**LUX 1.0 requirement Q9.2 with a UI dev phase of "Important-Test"**

In addition to being able to filter by the unit responsible for and only applicable when sorting search results by relevancy / scores, the users need a way to counter one unit's objects and works from dominating the search results whereby the unit's search results are not completely removed but rather diluted by those from other units.  A way we may be able to do this is to apply a negative boost/weight to specified units.  By also offering a positive boosting, one could also make objects and works from specific units more relevant. 

Would be good to offer a generic implementation such that the front end could enable users to do this to other criteria as well.

**Comment by brent-hartwig** [comment]
@azaroth42 and @roamye, this might have gotten easier to implement now that the documents identify the owners/sources.

cc: @clarkepeterf

**Comment by azaroth42** [comment]
If it's just for the objects/works, then yes that's probably fine. Not sure if functionality is needed though... the results lists are generally pretty reasonably ordered by relevance.

Might need it if/when we move to optic?

**Comment by brent-hartwig** [comment]
> Might need it if/when we move to optic?

Perhaps.

I'll leave present-day prioritization to @roamye.  I don't know if the ability to support this easier now may change opinions on whether this should still be slated as Future Work vs. Backlog.

**Comment by prowns** [comment]
From UAT -
Was part of original requirements, but decision now to close.  Facets provide this functionality, as does adv. search.
