### ISSUE TITLE
Paginate semantic facet requests

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#161]
_Same as #160 but for semantic facets._

**Problem Description:**

Each facet request returns all of the facet's values, leading to requests taking longer than necessary to process, response sizes being larger than necessary, and contributing to system instability.  This ticket's scope is limited to semantic facets.

**Expected Behavior/Solution:**
Paginate facet requests.  Default to 20 facet values.  Impose a maximum of 100 values per request.

Until the frontend and middle tier implement facet pagination, the frontend will be limited to the first page of facets, as defined by the backend.

**Requirements:**
Enable backend endpoint consumers to specify the page and page length.  Default to page 1 with a page length of 20.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
- [x] Backend requirements: See above
- [x] Middle tier requirements: https://github.com/project-lux/lux-middletier/issues/65
- [x] Frontend requirements: https://github.com/project-lux/lux-frontend/issues/252
- [ ] Are new regression tests required for QA - Amy

~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**

- Blocked By: Nothing
- Blocking: The associated frontend and middle tier tickets.

**Related Github Issues:**

#160: Same ticket but for non-semantic facets.
#162: Performance test targeting #160 if not also #161

**Related links:**

None

~~**Wireframe/Mockup:**~~
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by clarkepeterf** [comment]
Plan from Team Meeting 06/14/2024:

- Do pagination as is
- Allow facets to request up to 10000 values per page
- Remove `first` property from facets

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Closing looks good in PROD
