### ISSUE TITLE
Create new "DATA" tenant in DEV

### ISSUE THREAD

**Issue by jffcamp** [project-lux/lux-marklogic#164]
**Problem Description:**
We need an environment where we can test new datasets without disrupting the regular development flow. 

**Expected Behavior/Solution:**
Creating a new lux-data-dev tenant will allow new datasets and new code dependent on the data to be deployed and tested.

**Requirements:**
List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- ~[ ] Wireframe/Mockup - Mike~
- ~[ ] Committee discussions - Sarah~
- [x] Feasibility/Team discussion - Sarah
- Backend requirements -
   - [x] Increase storage - Xinjian
   - [x] Create the tenant - Peter
- Middle tier & Frontend - Seong
  - [x] Create new middle-tier and frontend
  - [x] DNS request - lux-data-dev.collections.yale.edu
- [x] Frontend requirements - Deploy frontend - Kameryn
- [x] Are new regression tests required for QA - Amy
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
N/A - this won't go to UAT and is intended for internal purposes

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
https://github.com/project-lux/lux-marklogic/pull/153
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**
- Frontend and middle tier: https://github.com/project-lux/lux-middletier/issues/63

**Related links:**

- These links can consist of resources, bugherds, etc.

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by clarkepeterf** [comment]
I don't think this needs to be reviewed as part of the normal UAT process. but the data-dev tenant is created and supports the following instance of LUX: https://lux-data-dev.collections.yale.edu/

**Comment by roamye** [comment]
If the data-dev tenant is created can this issue be closed? Or are we still missing the two boxes that are unchecked? 

@clarkepeterf @kamerynB

**Comment by clarkepeterf** [comment]
@roamye those steps are also done - I just checked them off - all good to close this item
