### ISSUE TITLE
Add Build Time Data Constant For Collection

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#167]
**Problem Description:**
We updated the indexes to use AATs instead of dataconstants. Therefore, we no longer need to receive a pipelineDataConsants.json file from the pipeline. However, the `collection` constant is defined in that file and is used in the via search facets. So, we'll have to generate the same constant at build time.

**Expected Behavior/Solution:**
Creat a new generation config for the constant

**Requirements:**
List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD
- [ ] ~Frontend requirements- TBD~
- [ ] ~Are new regression tests required for QA - Amy~
- [ ] ~Questions~
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**

- These links can consist of resources, bugherds, etc.

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by roamye** [comment]
@clarkepeterf what are the UAT links? or is this only reviewable in the backend?

**Comment by roamye** [comment]
@clarkepeterf Was this deployed?

**Comment by clarkepeterf** [comment]
@roamye  this was deployed. The best way I can think to prove it is  that the current [pipelineDataConstants.json](https://github.com/project-lux/lux-marklogic/blob/main/scripts/generateIndexConf/pipelineDataConstants.json) file contains the following line:
```
"collection":"https://lux.collections.yale.edu/data/concept/ef1b235c-ce4a-48ac-8820-b20fda63dc17",
```
(this is only visible in source code)

But the [data constants](https://lux-front-tst.collections.yale.edu/api/data-constants) in TST show a different LUX URI for "collection", because we are now generating it at runtime based on the Getty AAT URI

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
@clarkepeterf was this deployed to PROD? I am checking the data constants in PRD and this is what is shown below: 

`"collection": "https://lux-front-dev.collections.yale.edu/data/concept/2340bd83-22b4-4a39-ae46-ba0258e3a79d",`

wanted to confirm if that was correct before closing.

**Comment by clarkepeterf** [comment]
That is correct - it is deployed to PRD
