### ISSUE TITLE
Log additional details of failed searchWillMatch requests

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#177]
**Problem Description:**
During 7 Jun 24's performance test (#162), we observed five `JS-FATAL` instances that were all related to `searchWillMatch` requests.  The logs did not provide any insights on why the request failed or what the search criteria was.

**Expected Behavior/Solution:**

- [x] Pick an existing or new trace event, such as `LuxSearch` or `LuxSearchWillMatch`.  **Selected LuxSearch.**
- [x] If a new trace event, add to [default-group.json](https://github.com/project-lux/lux-marklogic/blob/main/src/main/ml-config/base/groups/default-group.json).  **No edit necessary.**
- [x] Add a try/catch block in `determineIfSearchWillMatch`.  In the catch block, when the selected trace event is enabled, log the request's search criteria and exception.
- [x] Update [mineBackendLogs.sh](https://github.com/project-lux/lux-marklogic/blob/main/scripts/logAnalysis/mineBackendLogs.sh) to surface failed `searchWillMatch` requests.

**Requirements:**
See above.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~- [] Wireframe/Mockup - Mike~
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements
~- [ ] Frontend requirements~
~- [ ] Are new regression tests required for QA - Amy~
- [x] Compels a performance test?  No.
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
Developer will be able to force an error and ensure the log entries are created and picked up by the log mining script.

**Dependencies/Blocks:**
While https://git.yale.edu/lux-its/ml-cluster-formation/issues/19 is not technically blocked by this, I recommend implementing it after this ticket.

**Related Github Issues:**
#183 could be implemented at the same time.

**Related links:**
None.

**Wireframe/Mockup:**
Not needed.

**Comment by brent-hartwig** [comment]
FYI @roamye

**Comment by xinjianguo** [comment]
@brent-hartwig do we have the strings to monitor yet?

**Comment by brent-hartwig** [comment]
No, but I can implement this ticket and #183 today.  I'll get back to you!

**Comment by brent-hartwig** [comment]
@xinjianguo, I updated https://git.yale.edu/lux-its/ml-cluster-formation/issues/19 for #177 and https://git.yale.edu/lux-its/ml-cluster-formation/issues/24 for #183 with the text to match on.

**Comment by brent-hartwig** [comment]
Implemented #177 and #183 together.  See PR https://github.com/project-lux/lux-marklogic/pull/197 for implementation details.
