### ISSUE TITLE
Extract query plan viewer into its own ML Gradle project

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#192]
Having the query plan viewer embedded in this repo incorrectly gives the impression that much of the backend is implemented in XQuery, when it is not:

![image](https://github.com/project-lux/lux-marklogic/assets/13734146/6d328857-de6b-4097-99d9-93d7ab3c9123)

The scope of this ticket is to extract it from this project and package it up as its own ML Gradle project.

**Comment by brent-hartwig** [comment]
This ticket impacts multiple repos.  By repo...

### lux-marklogic repo (public)

PR #195 extracts the query plan viewer from the lux-marklogic repo.  It also moves the remaining modules directly within the standard ml-modules directory, alleviating us from setting the `mlModulePaths` property.

Full list of property changes:

1. Delete the `mlModulePaths` property as the new value matches ML Gradle's default.  If one chooses to keep the property, set it to `src/main/ml-modules`.
2. Set the `mlConfigPaths` property value to `build/main/ml-config/base,build/main/ml-config/base-secured`.
3. Delete the `mlQueryPlanViewerPort` property.
4. Delete the `mlQueryPlanViewerAuthentication` property.

### ml-cluster-formation (private)

[PR #26](https://git.yale.edu/lux-its/ml-cluster-formation/pull/26) makes the above property edits to our environment-specific properties files.

@clarkepeterf and @xinjianguo, these changes will apply to backend release1.20 and later as soon as the above PR is merged into the release1.20 branch.  After that time, please update any copies of these files you may have.  If the `mlModulesPaths` property is not deleted or updated, the deployment will fail.  For quick reference, see [changes to gradle.properties](https://github.com/project-lux/lux-marklogic/pull/195/files#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19).

### query-plan-viewer (new)

@clarkepeterf, please create a new repo out of [query-plan-viewer.zip](https://github.com/user-attachments/files/15973431/query-plan-viewer.zip).  Up to you if private or public.  It comes with a README.md that is appropriate for all ages and audiences.

As this is a standalone ML Gradle project, it comes with its own `gradle.properties` file.  While we could create a new set of environment-specific ones within the ml-cluster-formation repo, I do not see the need.  The one I created for DEV overrode two properties: `mlHost` and `mlUsername`.

@clarkepeterf and @xinjianguo, now or later, we can **delete the query plan viewer app server from SBX, Blue, and Green** (restarts the cluster).  Its configuration will become obsolete as soon as the PR #195's changes are deployed.  Given the query plan viewer is not presently being used, I'm good with deleting its app server and not recreating it.  DEV's query plan viewer was created using the attached files.

**Comment by roamye** [comment]
Per uat I am closing this ticket as it is done.

**Comment by brent-hartwig** [comment]
@clarkepeterf, you may want to hold off on creating a standalone repo for the query plan viewer since we're rolling ML 11.3.0 out and it may have caught up and surpassed John Snelson's version.

**Comment by brent-hartwig** [comment]
BTW, mission accomplished!

![image](https://github.com/user-attachments/assets/fdecb3a7-e8d6-419d-b4a2-04afddad25c0)
