### ISSUE TITLE
Force Range Index for AutoComplete Fields Without Range Indexes

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#198]
**Problem Description:**
The eventName and eventPrimaryName fields currently do not have any Field Range Indexes - which are needed for autocomplete. 

**Expected Behavior/Solution:**
Force Range Indexes for these fields so that autocomplete can work

**Requirements:**

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**
Autocomplete is not being used - this is an ML only change. Just making sure this feature is not broken when it is consumed by the frontend.

**Dependencies/Blocks:**

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
~~- Blocking: Issues being blocked by the completion of the current issue.~~

**Related Github Issues:**

~~- Issues that contain similar work but are not blocking or being blocked by the current issue.~~

**Related links:**

~~- These links can consist of resources, bugherds, etc.~~

**Wireframe/Mockup:**
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by clarkepeterf** [comment]
@prowns @jffcamp 

This is a quick item. But I think it makes sense to move to next sprint as it requires an index update. I'd rather make the code update and be able to see the new index in the same milestone.

**Comment by roamye** [comment]
Is this unreviewable? @clarkepeterf

**Comment by roamye** [comment]
Approved by UAT 7/22

**Comment by roamye** [comment]
Closing as it has been deployed to PROD and is unreviewable.
