### ISSUE TITLE
Update advanced search config Person or Group label

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-marklogic#201]
**Problem Description:**
The Person or Group option should be updated to ensure consistency across tabs.

**Expected Behavior/Solution:**
The option will be "Person or Group Class".

**Requirements:**

- [x] Update the config

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - Kam
- [x] Frontend requirements - Kam/Amy
- [x] Are new regression tests required for QA - Amy
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22recordType%22%3A%22person%22%7D
- [PROD](https://lux.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22group%22%7D%5D%7D)

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- https://github.com/project-lux/lux-frontend/issues/282

**Related links:**
N/A

**Wireframe/Mockup:**
Expected advanced search option:
![Screenshot 2024-06-27 at 12 05 09 PM](https://github.com/project-lux/lux-frontend/assets/140102078/bbc8616a-6564-4907-9f95-33b8310f12eb)

**Comment by roamye** [comment]
Approved by UAT 7/22

**Comment by roamye** [comment]
Looks good in PROD. Closing.
