### ISSUE TITLE
Delete the personRoles endpoint

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#203]
**How can this be tested?**

Attempt to consume the `/ds/lux/personRoles.mjs` endpoint.  So long as #207 is also deployed, a 404 should be returned.  Endpoint documentation should also be removed from lux-backend-api-usage.md.  Note that the middle tier never exposed this backend endpoint; therefore, there are no frontend dependencies on this endpoint.

---

**Description**

The `crm:P14_carried_out_by` triples were removed from the Beta 2 dataset, over a year ago.  Events have a LUX alternative, but not people.  Until we commit to coming up with a different way, let's get rid of the associated code, which includes the `personRoles` data service and following function from utils.mjs.  Without the triples, it can only return an empty array.  The original use case for this endpoint was to facet search results by person/agent roles.

The middle tier does not presently code against the `personRoles` data service.  The next time it updates the generated proxies, this endpoint will be removed.  No need to do so in advance of a different backend API change.

```
// Return an array of objects describing the person's various roles.  Each object includes
// the role's IRI and the number of times the person has that role in the corpus.
function getPersonRolesInfo(personUri) {
  if (fn.docAvailable(personUri)) {
    const sparql = `
    prefix crm: <http://www.cidoc-crm.org/cidoc-crm/>
    SELECT ?role (COUNT(?role) AS ?count) WHERE {
      ?act crm:P2_has_type ?role ; 
           crm:P14_carried_out_by <${personUri}>  
    } GROUP BY ?role`;
    return Array.from(op.fromSPARQL(sparql).result());
  }
  return [];
}
```

**Comment by brent-hartwig** [comment]
Implemented in PR https://github.com/project-lux/lux-marklogic/pull/204, which should be merged into release1.20 after PR #199 is.

**Comment by roamye** [comment]
Per uat I am closing this ticket as it is done.
