### ISSUE TITLE
Investigate slow load into SBX on 2 Jul 24

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#218]
Some data loads have started to experience a rate slow down.  At first it seemed to be 2 to 2.5 hours into the load, possibly in environments with forest-level replication enabled.  More recently it has happened after four hours (91% - 93% complete), in SBX without forest-level replication.  I created this ticket as a dumping ground for data collected from SBX's 2 Jul 24 load.

| Characteristic | Value |
|--------------------------------|----------------|
| Start Time (UTC)               | 7/2/2024 13:23 |
| End Time (UTC)                 | 7/2/2024 18:50 |
| Total Execution Time (seconds) | 19857          |
| Target Env                     | SBX            |
| ML Version                     | 11.2.0         |
| Forests Replicated?            | No             |
| Source Machine                 | Pipeline       |
| Java Version                   | 11.0.23        |
| MLCP Version                   | 11.2.0         |
| Thread Count                   | 64             |
| Batch Size                     | 50             |
| Slowdown Percent               | 91             |
| Slowdown Time                  | 7/2/2024 18:08 |
| Duration before Slowdown       | 4:44:57        |

**Comment by brent-hartwig** [comment]
### ML Load Balancer Request Rate

Requests dropped off around 1800 UTC, implying but not confirming the slow down is on the requesting side.

![image](https://github.com/project-lux/lux-marklogic/assets/13734146/036e3d35-e41d-43c8-9606-aa6f0f9bf460)

**Comment by brent-hartwig** [comment]
### ML Logs

Documents were loaded via port 8000.

Request logs are not enabled for port 8000.  They were of interest as they capture request durations, and perhaps could have reflected whether ML was taking longer to process requests after the slow down.

Access logs are available.  They include 41,679,750 PUTs and capture times but not durations.  Not sure how informative 41m timestamps are.  The logs are too massive to attach here (1.1 GB compressed / 14.8 GB uncompressed).

8000's error logs are empty.

The main error logs are large and filled with debug- and info-level messages, likely mostly related to merging.

**Comment by brent-hartwig** [comment]
### MLCP

Rob questioned whether MLCP is having to retry requests and whether we could compare the load balancer request count to requests processed by ML.  As noted above, there were 41,679,750 PUTs, which translate to document insert attempts.  That number includes requests after the data load ended, and may include a handful of 401s.  We would need to select a period and get counts from 8000's access logs and the ML LB.

For future runs, we can also enable debug-level messages: https://docs.marklogic.com/11.0/guide/mlcp-guide/en/troubleshooting/enabling-debug-level-messages.html

**Comment by brent-hartwig** [comment]
### ML Monitoring History

13:15 - 19:00

![01-cpu](https://github.com/project-lux/lux-marklogic/assets/13734146/2c9be69b-5084-4c32-a04e-8b561ec2b8c4)
![02-io](https://github.com/project-lux/lux-marklogic/assets/13734146/3d5c07a0-daf3-4425-9c7d-b58821754060)
![03-memory](https://github.com/project-lux/lux-marklogic/assets/13734146/8aa4b67f-5c38-43e0-a687-039facc58e9c)
![04-xdqp](https://github.com/project-lux/lux-marklogic/assets/13734146/cce77402-6ad9-4066-801c-f5b4f29473e4)
![05-servers](https://github.com/project-lux/lux-marklogic/assets/13734146/53cefb45-af8a-4ec8-acb8-74aedbcfb519)
![06-network](https://github.com/project-lux/lux-marklogic/assets/13734146/726eac11-3294-4989-b6a3-56c0b7ce1ee0)
![07-database](https://github.com/project-lux/lux-marklogic/assets/13734146/73c14590-8d1d-4616-be10-637ec88b2463)

Exports:

[01-cpu.xls](https://github.com/user-attachments/files/16100617/01-cpu.xls)
[02-io.xls](https://github.com/user-attachments/files/16100618/02-io.xls)
[03-memory.xls](https://github.com/user-attachments/files/16100620/03-memory.xls)
[04-xdqp.xls](https://github.com/user-attachments/files/16100621/04-xdqp.xls)
[05-servers.xls](https://github.com/user-attachments/files/16100612/05-servers.xls)
[06-network.xls](https://github.com/user-attachments/files/16100614/06-network.xls)
[07-database.xls](https://github.com/user-attachments/files/16100615/07-database.xls)

**Comment by roamye** [comment]
fyi: This did not go through the UAT process and will have to be moved to prioritization review to be reviewed tomorrow.

**Comment by brent-hartwig** [comment]
@roamye, I'm pretty sure this can be closed.  I wanted a place to share everything I found on the ML side.  No one added anything from the other side, and is unlikely to do so.  We're also now tracking data loads in [Data Load Times](https://docs.google.com/spreadsheets/d/1uu6aL7yn047yyiZ4auujpTXnlwm01sgWZQ50ht-X4M4/edit?gid=1934153271#gid=1934153271) (private).

**Comment by roamye** [comment]
UAT 8/26 
OK with closing. Thanks.
