### ISSUE TITLE
Add Sets to Work Class Facet

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#222]
**Problem Description:**
The Work Class Facet needs to be able to display Sets. This was not included in the initial requirements in #140. But that can lead to situations like the following:

- https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22Set%22%7D%2C%7B%22name%22%3A%22saarinen%22%7D%5D%7D
  - "Set" is a valid value for the "recordType" field, but it is not a valid value for the Work Class facet. Therefore, now facets show up.

**Expected Behavior/Solution:**

Update the workDataTypeName index to include the following XPath: `/indexedProperties[dataType = 'Set']/dataType`

**Requirements:**

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22Set%22%7D%2C%7B%22name%22%3A%22saarinen%22%7D%5D%7D
  - This link should have the "Work Class" facet

~~**Dependencies/Blocks:**~~

**Related Github Issues:**
- #140 

**Related links:**
Bugherd: https://www.bugherd.com/projects/284041/tasks/2394

~~**Wireframe/Mockup:**~~

**Comment by roamye** [comment]
This is already in PROD. Proposing to close it on UAT 7/22.

**Comment by roamye** [comment]
Approved by UAT 7/22 to close as it is already in PROD.
