### ISSUE TITLE
Validation For Data Constants (from 762)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#23]
**Problem Description:**
Create validation scripts/gradle tasks for the following:

1. When a new dataset is deployed, check if all dataconstants still exist at their previous IRIs
    - this might be an issue for the pipeline (Rob)
2. When data constants are generated, provide a list of any constants whose values changed
    - This could be an update to scripts/generateIndexConf/getPipelineDataConstants.py 

**Expected Behavior/Solution:**
TBD

**Requirements:**
TBD

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Heather~~
~~- [ ] Committee discussions - Sarah~~
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

**Dependencies/Blocks:**

**Related Github Issues:**
- https://git.yale.edu/LUX/pipeline/issues/177
- https://git.yale.edu/lux-its/marklogic/issues/903

**Related links:**

**Wireframe/Mockup:**

**Comment by brent-hartwig** [comment]
@clarkepeterf, in the advent of the frontend and database indexing configuration changing to AATs, has this ticket become obsolete or perhaps need to morph?

**Comment by clarkepeterf** [comment]
I think this only applies to pipeline dataconstants which are not used anymore. Propose close.
