### ISSUE TITLE
Create Search Term for Part Of to connect Works that are Part of another Work 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#234]
**Problem Description:**
Front-end and middle tier want to display Part Of for Work records in both directions rather than in only one direction as it currently does.  

**Expected Behavior/Solution:**
Create a search term to allow for Part of to be searched/linked back to its original work. 

**Requirements:**
Search in both direction where a work record will ....
- link to works it is Part Of (currently does) 
- link back to works it is Part Of

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] ~Are new regression tests required for QA - Amy~
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
N/A - See front end tix. 

**Dependencies/Blocks:**
- Blocked By: https://github.com/project-lux/data-pipeline/issues/85 (triple) 
- Blocking: https://github.com/project-lux/lux-middletier/issues/79

**Related Github Issues:**
N/A

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2327

**Wireframe/Mockup:**
N/A - see FE ticket.

**Comment by clarkepeterf** [comment]
@roamye @prowns this issue  is unblocked now, as the required data should be available in the next dataset (2024-08-29)

**Comment by roamye** [comment]
@clarkepeterf Awesome - once the data is available can you update the UAT so it can pass prioritization review? It can then be moved into the 09/23 milestone if the uat is updated before 09/12.

**Comment by clarkepeterf** [comment]
@kkdavis14 I don't see the required triple in the data.

For example, for this record: https://lux-front-dev.collections.yale.edu/data/text/77a59f7f-227f-4e8d-8539-39fc39a15b3e 

It has the following in the JSON:
```
"part_of": [
{
"id": "https://lux-front-dev.collections.yale.edu/data/text/66b917f7-6908-43aa-8e0e-5d2f4b26424c",
"type": "LinguisticObject",
"_label": "Contributions."
}
]
```

The only triples I see that link to the same document as the `part_of` are below:
```
{
"triple": {
"subject": "https://lux.collections.yale.edu/data/text/77a59f7f-227f-4e8d-8539-39fc39a15b3e", 
"predicate": "https://lux.collections.yale.edu/ns/workAny", 
"object": "https://lux.collections.yale.edu/data/text/66b917f7-6908-43aa-8e0e-5d2f4b26424c"
}
}, 
{
"triple": {
"subject": "https://lux.collections.yale.edu/data/text/77a59f7f-227f-4e8d-8539-39fc39a15b3e", 
"predicate": "https://lux.collections.yale.edu/ns/any", 
"object": "https://lux.collections.yale.edu/data/text/66b917f7-6908-43aa-8e0e-5d2f4b26424c"
}
},
```

I would need another triple specific to the `part_of` relationship, not the `any`/`workAny` triples

**Comment by kkdavis14** [comment]
@clarkepeterf there's no "http://www.cidoc-crm.org/cidoc-crm/P106i_forms_part_of" triple in that document?
looking into it but I don't see the bug immediately...

**Comment by clarkepeterf** [comment]
@kkdavis14 It looks like the `elif` [here](https://github.com/project-lux/data-pipeline/blob/main/pipeline/sources/lux/marklogic/mapper.py#L538-L546) on lines 538-546 will never be triggered, because when `data["type"] == "LinguisticObject"` it will go into the `elif` on line 503.

**Comment by kkdavis14** [comment]
thanks @clarkepeterf you're right. I'll put in a PR but it won't make it in the current dataset being prepared right now.

**Comment by kkdavis14** [comment]
https://github.com/project-lux/data-pipeline/pull/149

**Comment by clarkepeterf** [comment]
Thank you @kkdavis14 🙂

**Comment by clarkepeterf** [comment]
Moving to next deployment as we will need the data update

**Comment by clarkepeterf** [comment]
@kkdavis14 will the dataset that is building now have the updates from https://github.com/project-lux/data-pipeline/pull/149 ?

**Comment by kkdavis14** [comment]
@clarkepeterf it should, yep!

**Comment by clarkepeterf** [comment]
@kkdavis14 are we meant to use the `http://www.cidoc-crm.org/cidoc-crm/P106i_forms_part_of` triple for this relationship?

**Comment by kkdavis14** [comment]
@clarkepeterf yes, that's the one we created for this.

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Closing as the FE looks good in PROD.
