### ISSUE TITLE
Remove the personRoles endpoint (from 776)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#24]
Problem Description:  Between the Beta 1 and Beta 2 datasets, the http://www.cidoc-crm.org/cidoc-crm/P14_carried_out_by triples were replaced by https://lux.collections.yale.edu/ns/eventCarriedOutBy triples, yet as explicit in the predicate name, only for events.

The code executed by the personRoles endpoint requires http://www.cidoc-crm.org/cidoc-crm/P14_carried_out_by for people.  Unless we want to add them back into the dataset, we cannot facet people by the roles they played as "that information is in the item/work (as above), and hence would require a facet that spans records."

We are not losing functionality offered in the Beta 1 release.  One may continue to facet "items/works by people and their role relative to the item/work" as that information is directly in the item and work documents, thereby not require these triples (or any others).

Until removed or the triples added, we may expect this endpoint to return an empty array.

Electing not to use the 'backwards-incompatible' label as neither the front end nor middle tier ever coded against this endpoint.

Scope includes deleting the endpoint, its documentation, and might as well take out `utils.getPersonRolesInfo`.

Proposed Solution:  Remove this endpoint along with other Activity Stream changes.

Testing: try to use endpoint  (add test) and make sure it fails. 

More info:

* [Discussion in Teams](https://teams.microsoft.com/l/message/19:GmLeQu1cBR40mfrno-l8lngg7RFCcJs8fvFIw-MJjIM1@thread.tacv2/1675261859610?tenantId=dd8cbebb-2139-4df8-b411-4e3e87abeb5c&groupId=4620eac6-0955-4c69-93e8-b493b21f0df6&parentMessageId=1675261859610&teamName=MarkLogic&channelName=General&createdTime=1675261859610&allowXTenantAccess=false)
* Related data pipeline ticket: https://git.yale.edu/LUX/pipeline/issues/231

**Comment by brent-hartwig** [comment]
Completed in #203.
