### ISSUE TITLE
Add Professional Activity Categorized As in Advanced Search 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#248]
**Problem Description:**
You can currently search for people or groups with a certain professional activity categorized as in simple search but this ALSO needs to be added to the Advanced Search. 

**Expected Behavior/Solution:**
Add the search functionality and a new single field `Professional Activity Categorized As` in Advanced Search which accepts other fields and include new Help Text. 

**Requirements:**
- Single field `Professional Activity Categorized As` will display as an option in Advanced Search. 
- Icon for AS will be a lightbulb such as Categorized As has.
- New single field will work with other single fields such as `Name`, `Anywhere`, `Broader Concept`.... Etc. 
- Help text will be added and display as: 
```
Help for Professional Activity Categorized As

Search for people and groups that carried out professional activities of the given categorization.

Learn more about LUX's advanced search capabilities and common search patterns.

View Advanced Search Help
```

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD
- [ ] Frontend requirements- Kam
- [ ] Are new regression tests required for QA - Amy
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- AS for [professional activity type of Pharamaceutical Industry](https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22professionalActivity%22%3A%7B%22name%22%3A%22Pharmaceutical+industry--United+States%22%7D%7D%5D%7D) should show a results page include the record below: 
- https://lux.collections.yale.edu/view/group/2e68492c-ef49-46ac-ad1a-4960ff46986d | TST: https://lux-front-tst.collections.yale.edu/view/group/2e68492c-ef49-46ac-ad1a-4960ff46986d

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**
- https://github.com/project-lux/lux-marklogic/issues/156

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2231

**Wireframe/Mockup:**
![example1_1](https://github.com/project-lux/lux-frontend/assets/163148482/7477b25c-5b9d-454e-b58d-b297d58dcc02)

**Comment by roamye** [comment]
@clarkepeterf - is this a quick fix? If it is we can add it to the next milestone 08/19

**Comment by clarkepeterf** [comment]
In order for this to become a field that can work with other terms inside it (`Name`, `Anywhere`, `Broader Concept`, etc.) we will need a new triple relating Agents and their Professional Activities. Is that something we can add @kkdavis14?

**Comment by kkdavis14** [comment]
I am struggling to find an example that exists for this type of data. Usually Professional Activities is a timespan or a location, which you can search for in AS. The example in the ticket doesn't exist like that anymore, as it was incorrect data.

**Comment by clarkepeterf** [comment]
@kkdavis14 For example - [this record](https://lux-front-tst.collections.yale.edu/data/person/40d3f96e-3abd-433c-a56c-c4debfbe74eb) has the following in its JSON, meaning they have a Professional Activity categorized as Education:
```
"carried_out": [
    {
        "type": "Activity",
        "classified_as": [
            {
                "id": "https://lux-front-tst.collections.yale.edu/data/concept/11c48705-1114-49aa-8896-c7490678b608",
                "type": "Type",
                "_label": "Professional Activities",
                "equivalent": [
                    {
                        "id": "http://vocab.getty.edu/aat/300393177",
                        "type": "Type",
                        "_label": "Professional Activities"
                    }
                ]
            },
            {
                "id": "https://lux-front-tst.collections.yale.edu/data/concept/3a30298b-37ce-40dd-aae4-4587994c54ba",
                "type": "Type",
                "_label": "Education"
            }
        ]
    }
]
```



If you search for People & Groups you can see a facet for Professional Activity Categorized As. If you select one of those facets, then each result should have an example like this in its data.

![Screenshot 2024-08-16 at 11 00 28 AM](https://github.com/user-attachments/assets/cc84d87e-86e4-4f2c-9a41-967ed54f0c29)


Can this be turned into a triple?

**Comment by kkdavis14** [comment]
yep https://github.com/project-lux/data-pipeline/issues/119

**Comment by clarkepeterf** [comment]
@roamye This will have to move to a future sprint, after https://github.com/project-lux/data-pipeline/issues/119 is completed

**Comment by roamye** [comment]
@clarkepeterf - sounds good, adding the 09/09 milestone as a check-in. We can move it again if needed.

**Comment by kkdavis14** [comment]
@clarkepeterf I was incorrect about the bug--the triple already exists: subject: Agent > property: "https://lux.collections.yale.edu/ns/typeOfProfessionalActivity" > object: classificationID

**Comment by clarkepeterf** [comment]
@kkdavis14  I still don't see that triple in this [example record](https://lux-front-tst.collections.yale.edu/data/person/40d3f96e-3abd-433c-a56c-c4debfbe74eb) - it has the following JSON, meaning this person has a Professional Activity categorized as Education:
```
"carried_out": [
    {
        "type": "Activity",
        "classified_as": [
            {
                "id": "https://lux-front-tst.collections.yale.edu/data/concept/11c48705-1114-49aa-8896-c7490678b608",
                "type": "Type",
                "_label": "Professional Activities",
                "equivalent": [
                    {
                        "id": "http://vocab.getty.edu/aat/300393177",
                        "type": "Type",
                        "_label": "Professional Activities"
                    }
                ]
            },
            {
                "id": "https://lux-front-tst.collections.yale.edu/data/concept/3a30298b-37ce-40dd-aae4-4587994c54ba",
                "type": "Type",
                "_label": "Education"
            }
        ]
    }
]
```
But there is not a `typeOfProfessionalActivity` triple in this document

**Comment by clarkepeterf** [comment]
@kkdavis14 looks like that triple is in the new 2024-08-29 dataset in SBX. This can be unblocked for next release. Marking for 09-23 @roamye

**Comment by clarkepeterf** [comment]
@kkdavis14 The typeOfProfessionalActivity triple is linked to all entries of `/carried_out/classified_as/`, so every person is linked to the generic "Professional Activities" concept.

For example, in this [example record](https://lux-front-tst.collections.yale.edu/data/person/40d3f96e-3abd-433c-a56c-c4debfbe74eb), there is the following JSON:

```
"carried_out": [
    {
        "type": "Activity",
        "classified_as": [
            {
                "id": "https://lux-front-tst.collections.yale.edu/data/concep11c48705-1114-49aa-8896-c7490678b608",
                "type": "Type",
                "_label": "Professional Activities",
                "equivalent": [
                    {
                        "id": "http://vocab.getty.edu/aat/300393177",
                        "type": "Type",
                        "_label": "Professional Activities"
                    }
                ]
            },
            {
                "id": "https://lux-front-tst.collections.yale.edu/data/concep7e804864-d784-4991-84d5-e05b823d3ce4",
                "type": "Type",
                "_label": "Education"
            }
        ]
    },
    {
        "type": "Activity",
        "classified_as": [
            {
                "id": "https://lux-front-tst.collections.yale.edu/data/concep11c48705-1114-49aa-8896-c7490678b608",
                "type": "Type",
                "_label": "Professional Activities",
                "equivalent": [
                    {
                        "id": "http://vocab.getty.edu/aat/300393177",
                        "type": "Type",
                        "_label": "Professional Activities"
                    }
                ]
            },
            {
                "id": "https://lux-front-tst.collections.yale.edu/data/concepb1ae78c7-eb12-4496-9c09-7ad0ffb5f814",
                "type": "Type",
                "_label": "Leadership"
            }
        ]
    }
]
```

And the following triples:
```
{
    "triple": {
        "subject": "https://lux.collections.yale.edu/data/person/40d3f96e-3abd-433c-a56c-c4debfbe74eb",
        "predicate": "https://lux.collections.yale.edu/ns/typeOfProfessionalActivity",
        "object": "https://lux.collections.yale.edu/data/concept/11c48705-1114-49aa-8896-c7490678b608"
    }
},
{
    "triple": {
        "subject": "https://lux.collections.yale.edu/data/person/40d3f96e-3abd-433c-a56c-c4debfbe74eb",
        "predicate": "https://lux.collections.yale.edu/ns/typeOfProfessionalActivity",
        "object": "https://lux.collections.yale.edu/data/concept/7e804864-d784-4991-84d5-e05b823d3ce4"
    }
},
{
    "triple": {
        "subject": "https://lux.collections.yale.edu/data/person/40d3f96e-3abd-433c-a56c-c4debfbe74eb",
        "predicate": "https://lux.collections.yale.edu/ns/typeOfProfessionalActivity",
        "object": "https://lux.collections.yale.edu/data/concept/11c48705-1114-49aa-8896-c7490678b608"
    }
},
{
    "triple": {
        "subject": "https://lux.collections.yale.edu/data/person/40d3f96e-3abd-433c-a56c-c4debfbe74eb",
        "predicate": "https://lux.collections.yale.edu/ns/typeOfProfessionalActivity",
        "object": "https://lux.collections.yale.edu/data/concept/b1ae78c7-eb12-4496-9c09-7ad0ffb5f814"
    }
}
```

I would expect the generic "Professional Activities" (https://lux.collections.yale.edu/data/concept/11c48705-1114-49aa-8896-c7490678b608) classification to not exist in the triples.

We filter this out in the Marklogic indexes, using the following XPath: `/json/carried_out/classified_as[not(./equivalent/id='http://vocab.getty.edu/aat/300393177')]/id`

It's not causing any issues right now, but I think it would be better to remove it if possible.

**Comment by kkdavis14** [comment]
@clarkepeterf sorry about that, put a PR in to not add it in the future

**Comment by roamye** [comment]
Approved by UAT 9/27

**Comment by roamye** [comment]
Looks good in PROD. Closing.
