### ISSUE TITLE
Update Is Online facet to add up to total results for works 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#250]
**Problem Description:**
The Is Online facet does not add up to the total amount of work results for the works tab. 

**Expected Behavior/Solution:**
The Is Online values `Yes` and `No` will add up to the total amount of work results. 

**Requirements:**
- The sum of Yes and No records in the Is Online facet need to add up to the total number of results for the Works tab. 
- Re-index the facet to include sets. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD
- [x] Frontend requirements- TBD
- [x] Are new regression tests required for QA - Amy | No, we don't currently check on the Counts. Should we? It to specific and it is not done for any other facets.  
- [x] Questions
- Why is this happened? and what needs to be fixed in the ML side for this to work? | Answer: Needs to include the sets. 

**UAT/LUX Examples:**
- https://lux-front-tst.collections.yale.edu/view/results/works?facetRequest=true&pf=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A1%7D%5D%7D&pp=1&q=%7B%22text%22%3A%22sun%22%2C%22_lang%22%3A%22en%22%7D&sq=sun

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2432

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by roamye** [comment]
7/30 TF: 
Needs to be re-indexed to include the sets

**Comment by clarkepeterf** [comment]
@kkdavis14 can Sets be public domain?

The index for the "Are in the Public Domain" search term currently only applies to VisualItem and Linguistic Objects. If it can apply to Sets, I can update that as well

![Screenshot 2024-10-16 at 5 19 50 PM](https://github.com/user-attachments/assets/86acd95c-7674-4167-a218-124845c6c919)

**Comment by kkdavis14** [comment]
@clarkepeterf No, Sets don't have the `subject_to` property necessary to carry any rights information.

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in prod. Closing.
