### ISSUE TITLE
Update Help Text for all Class Data Types 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#251]
**Problem Description:**
The Class Data Types `Work Class`, `Event Class`, `Object Class`, and `Concept Class` required help text for every selection of its value as listed in ML Issues [138](https://github.com/project-lux/lux-marklogic/issues/138), [139](https://github.com/project-lux/lux-marklogic/issues/139), [140](https://github.com/project-lux/lux-marklogic/issues/140) and [141](https://github.com/project-lux/lux-marklogic/issues/141). However, adding help text to each value requires new functionality that DNE. 

**Expected Behavior/Solution:**
- Current data class help text will be updated to include value help text Instead of creating a new functionality to add help text for each value. This includes: `Work Class`, `Event Class`, `Object Class`, `Person and Group Class` and `Concept Class` 

**Requirements:**
- Help text will be updated as follows: 

> **Object Class:**
> Search for records categorized as either a "Physical Object" or a "Digital Object". Physical Objects are physical items, such as paintings, sculptures, fossils and other specimens, and archival objects. Individual physical copies of books are included in this class. Digital Object are digital items, such as internet resources (datasets, e-books, and other digital files). Digitized images of collection items that are physical objects can be found with the “Is Online” facet on Physical Objects

> **Work Class:**
>  Search for records categorized as either a "Visual Work" or a "Textual Work. Visual Works are Works that are primarily visual, such as the images shown by paintings or photographs, sculptures, or other non language oriented creative expressions. Textual Works are Works that are primarily textual or otherwise convey information via human language. An Object may include both visual and textual works, such as a poster with graphics and text. In addition, Textual Works encompasses most items from the Library collections, including posters, artworks, musical scores, video and sound recordings.

> **Event Class:** 
> Search for records categorized as either a "Period" or an "Activity". Period are Events that have the class of Period, which consists of a Time Period, as opposed to other human-caused activities. Activity are Events that have the class of Activity, which consists of events such as Exhibitions or other collections-related activities.

> **Concept Class**
> Search for records categorized as either a "Measurement Unit", "Language", "Material", "Currency" or a "General Concept". Measurement Unit are Concepts that are used as the unit of a measurement, such as inches, seconds, kilograms or bytes. Language are Concepts that represent human-spoken languages, such as English, Spanish or Latin. Material are Concepts that represent a class of physical material, such as bronze, paper, or agate. Currency are Concepts that represent monetary currencies, such as dollars, euros, or francs. General Concept are Concepts that represent more general ideas or subjects, which excludes the more specific classes of Measurement Unit, Language, Material, and Currency.

> **Person or Group Class**
> Search for records categorized as either a "Person" or a "Group". Person is an individual either real or fictionalized. Group is an organization, either real or fictionalized, with one or more members. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- Should we do this for Person or Group Class? Yes 

**UAT/LUX Examples:**

- [Objects TST](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22HumanMadeObject%22%7D%5D%7D)
- [Works TST](https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22recordType%22%3A%22VisualItem%22%7D)
- [Concepts TST](https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22recordType%22%3A%22Currency%22%7D)
- [Events TST](https://lux-front-tst.collections.yale.edu/view/results/events?q=%7B%22recordType%22%3A%22Period%22%7D)
- [Person & Group TST](https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22recordType%22%3A%22person%22%7D)

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**
- https://github.com/project-lux/lux-marklogic/issues/141
- https://github.com/project-lux/lux-marklogic/issues/140
- https://github.com/project-lux/lux-marklogic/issues/139
- https://github.com/project-lux/lux-marklogic/issues/138

**Related links:**

**Wireframe/Mockup:**
![image](https://github.com/user-attachments/assets/81c3702d-b31f-429f-b7a1-d7f0ca284d48)

![image](https://github.com/user-attachments/assets/88df9bbb-799f-4bcb-8681-d30edf9225e0)
![image](https://github.com/user-attachments/assets/130313a1-7fbc-48cf-bc58-3b53efdeec7f)
![image](https://github.com/user-attachments/assets/edc4905d-9455-4797-8062-a1f97ec114bb)
![image](https://github.com/user-attachments/assets/08b012c1-a079-4db1-b864-b12fb7f960c0)

**Comment by roamye** [comment]
Question - do we want to do the same thing for People & Group Class? I also worry about how long the Help text will have to be since we are adding value information into it. Specifically the Concept Class help text.

**Comment by clarkepeterf** [comment]
@roamye With current functionality, I cannot add newlines to the help text. So the descriptions will all show up as one giant block of text without blank lines in between them. 


Also, I do think it makes sense to add to People & Group Class as well.

**Comment by roamye** [comment]
@clarkepeterf  - ahh, so it would display like this instead: 

![image](https://github.com/user-attachments/assets/3dc2e489-787c-4dc6-a462-aa08e594dc1d). 

@prowns - possible help text: search for records categorized as a "Person" or a "Group". Person is an individual either real or fictionalized. Group is an organization, either real or fictionalized, with one or more members.

**Comment by clarkepeterf** [comment]
@roamye yes it will look like that example image

**Comment by clarkepeterf** [comment]
@prowns @roamye  I'm already updating help text and this is a quick issue so I'm pulling it into this release

**Comment by roamye** [comment]
@clarkepeterf - OK I updated the help text/mockups above to also include the person or group text.

**Comment by roamye** [comment]
Approved by UAT 8/7

**Comment by roamye** [comment]
Looks good in PROD. Closing.
