### ISSUE TITLE
Backup the security database separately and verify ability to restore

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#258]
> [!NOTE]
> Does not require UAT.  Should be verified by one with ML log access (and S3?) after deployed and has had a chance to run.

**Problem Description:**
At present, the scheduled backups for the lux-content database include the security database.   That's fine except we are more likely to reload the lux-content database the restore its backup.  We do not have a "reload" option for the security database.  We are also yet to validate our backups by restoring one.

**Expected Behavior/Solution:**
- Seperate the lux-content database backups from the security database and validate the ability to restore the backup. 

**Requirements:**
This tickets scope: 
- [ ] Exclude the security database from the lux-content backups.
- [ ] Configure backup schedules for the security database.  I'm leaning towards daily full backups.
- [ ] Restore the backup of the security database and verify the outcome.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~- [ ] Wireframe/Mockup - Mike~
~- [ ] Committee discussions - Sarah~
~- [ ] Feasibility/Team discussion - Sarah~
- [ ] Backend requirements - TBD
~- [ ] Frontend requirements- TBD~
~- [ ] Are new regression tests required for QA - Amy~
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
N/A

**~Wireframe/Mockup:~**
~Place wireframe/mockup for the proposed solution at end of ticket.~

**Comment by xinjianguo** [comment]
on "Exclude the security database from the lux-content backups."

@brent-hartwig I don't see that the Security database is currently being backed up along with the lux-content db.

**Comment by brent-hartwig** [comment]
@xinjianguo, can you check the Forests directory in one of the backups?  Here is from my local backup:

![image](https://github.com/user-attachments/assets/f39891cc-5d0f-463b-aa9f-1bc45f402158)

**Comment by brent-hartwig** [comment]
@xinjianguo, the `backup-security-database` properties in /src/main/ml-config/base/databases/content-database.json need to be set to false.

**Comment by xinjianguo** [comment]
@brent-hartwig indeed, that deep!

![Screen Shot 2024-11-19 at 10 59 10 AM](https://github.com/user-attachments/assets/66b1518a-8567-4943-b909-274b3d3c7257)

**Comment by xinjianguo** [comment]
@brent-hartwig I am setting up a local ML instance on my desktop, but mlLoadModules keeps failing. Do I need to run the enableSSL step for a development env?

**Comment by xinjianguo** [comment]
@brent-hartwig We will apply the changes with 
./gradlew -i mlDeployDatabases
after the new release 1.30.0 is finalized.

Do you think it is save to run the task to all environments without need to reload data? I guess yes but would like to confirm with you.

**Comment by brent-hartwig** [comment]
@xinjianguo, so long as the [database index configuration](https://github.com/project-lux/lux-marklogic/blob/release1.30/config/contentDatabaseConfGenerated.json) did not also change, you can run `mlDeployDatabases` without initiating a re-indexing job (which would compel you to reload instead).  From the looks of it, that file has *not* changed.

**Comment by xinjianguo** [comment]
apply the changes LUX envs
https://git.yale.edu/lux-its/ml-cluster-formation/issues/64

**Comment by roamye** [comment]
Approved by UAT. 

@xinjianguo - can you confirm/verify this works?

**Comment by brent-hartwig** [comment]
@roamye and @xinjianguo, this has not reached two environments.

* 🟢 SBX
* 🟢 DEV
* 🔴 Green (TST): should be deployed by now.
* 🟡 Blue (PROD): not expected until after the next b/g switch.

**Comment by roamye** [comment]
Thanks for the update @brent-hartwig. 

@xinjianguo - once it reaches TST/PROD, please verify, thank you.

**Comment by xinjianguo** [comment]
@roamye green was configured and has been verified,
![Screenshot 2024-12-10 at 11 27 23 AM](https://github.com/user-attachments/assets/44069036-16d5-4155-a7a8-a6fe699c9556)

blue was just updated, will be verified tomorrow

**Comment by roamye** [comment]
@xinjianguo - has blue been verified?

**Comment by xinjianguo** [comment]
@roamye yes blue is verified, I am closing this ticket
