### ISSUE TITLE
Instead of LUX Environment Overview Spreadsheet, Pull Info Dynamically

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#264]
**Problem Description:**
The LUX Environment Overview Spreadsheet must be updated manually. This means it can be out of date if not updated along with code deployment, or subject to user error when entering data.

**Expected Behavior/Solution:**

Instead of using the spreadsheet we could create a webpage that interacts with API endpoints in Jenkins deployments or the applications themselves to display the correct info.

**Requirements:**
- [ ] Frontend / Middletier versions available here: https://tman-api-tst.collections.yale.edu/api/jenkins/versions/lux
  - [ ] Add info about what ML Host and Ports are being used 
- [x] ML code version can be a constant that is hardcoded with each release 
- [x] Data version can be grabbed from the `/admin/conversion-date` property in the data
  ~~- [ ] Optional: Include file in each dataset that has a consistent URI?~~
- [x] ML server version can be retrieved by calling `xdmp.version()`
- [x] ML endpoint(s) to get code, data and server versions
- [ ] UI to visualize all of this data in a table
- [ ] Where to host?

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**
- https://docs.google.com/spreadsheets/d/1uu6aL7yn047yyiZ4auujpTXnlwm01sgWZQ50ht-X4M4/edit?gid=1021623781#gid=1021623781
- https://tman-api-tst.collections.yale.edu/lux-env 

Note: Green doesn't have the ML code to display versions right now. We don't want to update the code in PRD, so Green will show errors until after the next blue-green switch (on October 1st) when we can update it.

**Dependencies/Blocks:**

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
~~- Blocking: Issues being blocked by the completion of the current issue.~~

**Related Github Issues:**

~~- Issues that contain similar work but are not blocking or being blocked by the current issue.~~

**Related links:**

~~- These links can consist of resources, bugherds, etc.~~

**Wireframe/Mockup:**
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by roamye** [comment]
@clarkepeterf - I added the LUX environment spreadsheet into the UAT section. Before any environments change we should take a screenshot of the current spreadsheet & then review if the updated spreadsheet is different from the screenshot with accurate updates. 

If you have any other ideas for UAT let me know. This is one approach we can use.

**Comment by clarkepeterf** [comment]
Code to grab data version from a document:

```
fn.head(cts.doc(fn.head(sem.sparql(`
prefix la: <https://linked.art/ns/terms/>

SELECT DISTINCT ?objectIri WHERE {
  ?objectIri la:equivalent <http://vocab.getty.edu/ulan/500303558> ;
}
`)).objectIri).xpath('/admin/conversion-date')).toString()
```

There should always be a document(s) equivalent to Yale University in the LUX dataset

**Comment by clarkepeterf** [comment]
@gigamorph I have two questions for you:

1. Could you add the ML host and port number used by each environment to https://tman-api-tst.collections.yale.edu/api/jenkins/versions/lux? (Or point me to the code so I can make that update?)
 2. Is there a spot on that tman server or somewhere I can host a static html page to display this environment info?

**Comment by roamye** [comment]
Approved by UAT 9/27

**Comment by roamye** [comment]
Closing as this was implemented and the url works fine.
