### ISSUE TITLE
Research: Show all links in Related People and Groups return 0 results.

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#267]
**Problem Description:**
The accordion Related People and Groups has show all [num] links which display a certain number. However, upon clicking this link it will bring a search result of 0 results. 

This ticket serves as a research ticket to investigate why this is happening and what solution can be done to fix it. 
There is a possibility this could be caused by archives. 

**Expected Behavior/Solution:**
TBD based on investigation. 

**Requirements:**
TBD based on investigation.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- https://lux-front-tst.collections.yale.edu/view/person/cc98b557-f401-4aac-a30f-c8c445c228b7 (fourth page in the accordion for YPM and Yale University) 

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2452

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by brent-hartwig** [comment]
@roamye, is this still reproducible?  Here are the steps I took:

1. Started at https://lux-front-dev.collections.yale.edu/view/person/cc98b557-f401-4aac-a30f-c8c445c228b7
2. Expanded the Related People and Groups accordion.
3. Clicked Next to get to the last page.
4. Clicked on the [Yale University link](https://lux-front-dev.collections.yale.edu/view/results/works?q={%22AND%22:[{%22OR%22:[{%22AND%22:[{%22aboutAgent%22:{%22id%22:%22https://lux.collections.yale.edu/data/group/13e8c131-6186-45ee-af65-890f133aa51f%22}},{%22createdBy%22:{%22id%22:%22https://lux.collections.yale.edu/data/person/cc98b557-f401-4aac-a30f-c8c445c228b7%22}}]}]}]}&searchLink=true): there is one search result, as advertised on the entity page.
5. Back on the entity page, clicked on the [YPM link](https://lux-front-dev.collections.yale.edu/view/results/works?q={%22AND%22:[{%22OR%22:[{%22AND%22:[{%22aboutAgent%22:{%22id%22:%22https://lux.collections.yale.edu/data/group/25608b89-52bf-4062-a554-d500a4f6b7fe%22}},{%22createdBy%22:{%22id%22:%22https://lux.collections.yale.edu/data/person/cc98b557-f401-4aac-a30f-c8c445c228b7%22}}]}]}]}&searchLink=true).  Here too, there is one search result which is what the entity page stated.

**Comment by brent-hartwig** [comment]
@clarkepeterf or @kkdavis14, can you think of a code or data change that could have resolved this disconnect between related lists and search results?  No biggie if not, but if we can document the resolution, all the better.  If data-related, it would have been after 2 Aug, when this ticket was submitted.

**Comment by kkdavis14** [comment]
@brent-hartwig I connected two separate Remington records via reconciliation--that might have done it?

**Comment by roamye** [comment]
@kkdavis14, @brent-hartwig - is the reconciliation of Remington a sufficient change to close this issue? or is more time needed to investigate the data-change that fixed this?

**Comment by brent-hartwig** [comment]
I'm fine with giving the bug a free pass this time.  If it comes back, we can dig in.

**Comment by clarkepeterf** [comment]
@kkdavis14 If the Remington records were combined via reconciliation, is it possible that the [Charles Lee Remington Archives Record](https://lux-front-tst.collections.yale.edu/view/set/0adf0b33-8e5d-45ff-accd-d72e30175427) was pointing to a non-existent ID for Remington?

**Comment by kkdavis14** [comment]
@clarkepeterf oh yah, that makes sense. agreed with Brent, fine to close.

**Comment by clarkepeterf** [comment]
Closing given consensus above
