### ISSUE TITLE
Make partOf field for Works (archives) available in AS

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#276]
**Problem Description:**
There is a work (archive) partOf field to describe archival sets being part of other sets. It is not available in AS right now. We would like it in AS
**Expected Behavior/Solution:**
Add AS field for this.

It can be done with as a hopWithField term with the following triple: `https://linked.art/ns/terms/member_of`

**Requirements:**

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**

**Related Github Issues:**

**Related links:**

**Wireframe/Mockup:**

**Comment by prowns** [comment]
Need to clarify what he purpose of this ticket is.  There was a teams chat.  Is this making archives available.  @roamye - add to ticket forming.  There is no set class at the top level.  Moving to forming to work out the details.

**Comment by clarkepeterf** [comment]
@prowns the purpose of this ticket is that Archival Sets are considered Works and can show up in Works results. e.g. [these results](https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22text%22%3A%22florida%22%2C%22_lang%22%3A%22en%22%7D&sq=florida&wp=1&wf=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22Set%22%7D%5D%7D&facetRequest=true)

These Archival Sets can be part of other Sets, so the goal of this ticket is to add a "Part Of" field in advanced search to query based on the Sets which the Archive is part of.

[This page](https://lux-front-tst.collections.yale.edu/view/set/82a80529-9994-476b-b0aa-171b308774ef) shows the hierarchy of an Archival Set (so you can see how we could traverse Part Of sets)

**Comment by clarkepeterf** [comment]
Propose close as this is a dupe of #94
