### ISSUE TITLE
update ML to not require additional steps after a data load. 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#281]
**Problem Description:**
From this [teams conversation](https://teams.microsoft.com/l/message/19:351e0281aaa144d0812b960d216958c6@thread.tacv2/1723476515506?tenantId=dd8cbebb-2139-4df8-b411-4e3e87abeb5c&groupId=4620eac6-0955-4c69-93e8-b493b21f0df6&parentMessageId=1723476515506&teamName=ML%2F%20Cultural%20Heritage%20Support&channelName=1%20-%20LUX_ML&createdTime=1723476515506), New Data in SBX was not working properly as it affected the Responsible Units Facet. 

**Expected Behavior/Solution:**
change ML so additional steps such as ,regenerating internal data constants, is no longer needed after a data load. 

**Requirements:**
- Update ML to remove the need for the additional step after the data load. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] ~Are new regression tests required for QA - Amy~
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- https://lux-front-sbx.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22oboe%22%2C%22_lang%22%3A%22en%22%7D&sq=oboe 
- PRD: https://lux.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22oboe%22%2C%22_lang%22%3A%22en%22%7D&sq=oboe

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
Bugherd: https://www.bugherd.com/projects/284041/tasks/2491

~**Wireframe/Mockup:**~
~Place wireframe/mockup for the proposed solution at end of ticket.~

**Comment by roamye** [comment]
@clarkepeterf - UAT is possibly checking the responsible unit facet after a new data is loaded?

**Comment by clarkepeterf** [comment]
Probably - the department URI may not always change (which is why we have to re-load) - but it usually does

**Comment by clarkepeterf** [comment]
This is solved by https://github.com/project-lux/lux-marklogic/issues/290 - propose close

**Comment by roamye** [comment]
Approved by UAT to close
