### ISSUE TITLE
Create search term for Works that are about Concepts

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#282]
**Problem Description:**
To support the modification of the HAL Link `Related Works` , a search term is needed to search for work records that are about a concept. 

Note: Set up is similar to ML #66. 

**Expected Behavior/Solution:**
- Create Search Term to search for Works that are about a Concept record. 

**Requirements:**
- Search term will search for all Works records that are about a Concept record. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] ~Are new regression tests required for QA - Amy~
- [ ] ~Questions~

**UAT/LUX Examples:**
- See FE/MT tix. 

**Dependencies/Blocks:**
- Blocking: https://github.com/project-lux/lux-middletier/issues/91 which blocks 
- https://github.com/project-lux/lux-frontend/issues/344

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2492

**~Wireframe/Mockup~:**
~Place wireframe/mockup for the proposed solution at end of ticket.~

**Comment by roamye** [comment]
dupe of: https://github.com/project-lux/lux-marklogic/issues/269

**Comment by prowns** [comment]
Returning to forming - this ticket is not formed correctly.  Search Term for Works about Events (see bugherd for example)

**Comment by roamye** [comment]
Approved by UAT 9/12 to close
