### ISSUE TITLE
Remove Collection Sets from ByUnit2

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#283]
**Problem Description:**
The ByUnit 2 environment: https://lux-byunit2.collections.yale.edu/, displays 15 works in the infographic which cannot be found through simple search. 

It was discovered that these works can be found through advanced search BUT this are departmental sets rather than archives. 

**Expected Behavior/Solution:**
Update /stats endpoint so that it doesn't include collection sets.

Remove Collection Sets from the Works count infographics.  

**Requirements:**
- Remove collection sets from the Works count infographics
- Infographics will display 0 Works after removal of collection sets. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- Should another tab for "sets" be added to include special collections, exhibitions collections, archives, and departmental collections? 

**UAT/LUX Examples:**

- https://lux-byunit2.collections.yale.edu/
- AS | [Work Class Set ](https://lux-byunit2.collections.yale.edu/view/results/works?q=%7B%22recordType%22%3A%22Set%22%7D)
- AS | [Work Class Set Created by PM](https://lux.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22Set%22%7D%2C%7B%22createdBy%22%3A%7B%22name%22%3A%22peabody+museum%22%7D%7D%2C%7B%22NOT%22%3A%5B%7B%22carriedBy%22%3A%7B%22memberOf%22%3A%7B%22name%22%3A%22archives%22%7D%7D%7D%5D%7D%5D%7D)

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**
- Bugherd: https://www.bugherd.com/projects/404004/tasks/1

**Wireframe/Mockup:**
Current: 
*lists 15 works 

Expected: 
![image](https://github.com/user-attachments/assets/01054676-1b7a-44a8-9292-b21c682882b2)

**Comment by clarkepeterf** [comment]
@kkdavis14 Do we only want Sets that are Archives to be included in the counts in the infographic? Do we also want to remove non-archives from Work results?

**Comment by clarkepeterf** [comment]
@kkdavis14 I've deployed a code change to by-unit2 that removes them from the infographic. Technically they are still searchable via some advanced searches: https://lux-byunit2.collections.yale.edu/view/results/works?q=%7B%22OR%22%3A%5B%7B%22hasDigitalImage%22%3A0%7D%5D%7D.

Let me know if that's what we want. There's a way to remove them from search if we want that as well

**Comment by kkdavis14** [comment]
I think still being findable via AS is fine--or at least, that wasn't part of their original request. thanks!

**Comment by roamye** [comment]
good to close, by-unit is updated. closing.
