### ISSUE TITLE
Update place relatedToConcept to remove Place of Publication relationship. 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#284]
**Problem Description:**
 `Place of Publication` and `Published At this Place` relationships are not desired in Related Lists.  ~https://github.com/project-lux/lux-frontend/issues/343~, the related lists will need to be updated. 

**Expected Behavior/Solution:**
Place of publication will no longer be a part of the related list: https://lux-front-tst.collections.yale.edu/api/related-list/place?name=relatedToConcept&uri=https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2Fd067d500-e6ea-4da2-9a2d-18bcd58e21dc 

**Requirements:**
- update related lists to no longer include the `Place of Publication` or `Published At this Place` relationships.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- This concept's Related Locations in TST should not have any `Place of Publication` relationships: https://lux-front-tst.collections.yale.edu/view/concept/d067d500-e6ea-4da2-9a2d-18bcd58e21dc 
-  This concept's Related Locations in PRD does have`Place of Publication` relationships: https://lux.collections.yale.edu/view/concept/d067d500-e6ea-4da2-9a2d-18bcd58e21dc 

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- ~FE: https://github.com/project-lux/lux-frontend/issues/343~ (not necessary) 

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2493

**Wireframe/Mockup:**
Current: 
![image](https://github.com/user-attachments/assets/df9c9cc7-47dc-4772-9612-0bd042292683)

Updated: 
![image](https://github.com/user-attachments/assets/1eb39687-c9f4-4897-8850-6073d3c7daf7)

**Comment by clarkepeterf** [comment]
@azaroth42 
@roamye 

I have a couple of questions:
1. The ticket explicitly mentions removing "Place of Publication" relationships from the **Related Locations** list on **Concept** pages. Do we also want to remove them from the **Related Locations** list on **Agent** and **Place** pages?
2. Do we want to also remove "Published At" relationships on **Place** pages? E.g. on the page for [New York](https://lux-front-dev.collections.yale.edu/view/place/f23964ce-4599-4029-afa3-c6df68871ddc):
  - <img width="1130" alt="Screenshot 2024-10-09 at 11 34 57 AM" src="https://github.com/user-attachments/assets/dffec31d-6eba-47d0-858d-26ce366c7904">

**Comment by roamye** [comment]
@clarkepeterf - bringing this to uat discussion tomorrow. will update you with answers afterwards.

**Comment by azaroth42** [comment]
IMO remove all place-of-publications from all related lists.

**Comment by clarkepeterf** [comment]
@azaroth42 Thanks, I'm going to interpret this as both 1 and 2 from [my comment above](https://github.com/project-lux/lux-marklogic/issues/284#issuecomment-2402677267).

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in prod. closing.
