### ISSUE TITLE
Remove Dependence on Data Constants

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#290]
**Problem Description:**
Stop ML from being dependent on data constants

**Expected Behavior/Solution:**
ML no longer needs to generate data constants to function properly

**Requirements:**
Change the following:
- [x] Change Via Search Facets to use AATs
- [x] Change Similar queries to use AATs
- [x] Change model / profileDocLib to use AATs
  - ~~partially complete, issue with language identifiers~~
- [x] Remove facet request thresholds (mentioned in xhttps://github.com/project-lux/lux-marklogic/issues/179)

~~**Needed for promotion:**~~
~~If an item on the list is not needed, it should be crossed off but not removed.~~

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- All pages continue to work as normal

~~**Dependencies/Blocks:**~~
~~N/A~~

~~**Related Github Issues:**~~
~~N/A~~

~~**Related links:**~~
~~- N/A~~

~~**Wireframe/Mockup:**~~
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by roamye** [comment]
@clarkepeterf - before moving this to backlog please move it to prioritization review first so it can follow the UAT process. Moving this to prioritization review so it can be reviewed tomorrow.

**Comment by clarkepeterf** [comment]
@brent-hartwig @azaroth42 Do we need to generate a dynamic list of language identifiers based on the data, or can we have a pre-selected list of supported languages?

Note:
- Currently there are 768 language data constants in DEV.
- Currently the frontend never passes a `lang` argument when requesting a document, so it always defaults to `en`

**Comment by brent-hartwig** [comment]
@clarkepeterf, thinking ahead to when consumers start specifying a language, we could make an adjustment now: fallback on the likes of English when the data pipeline did not provide a constant for the requested language.  We have such fallback logic in `getIdentifiedByPrimaryName` but not `getLanguageIRI`.  The latter will presently throw an exception if we do not have the associated constant.  We also have `hasLangaugeIRI` which will not throw an exception; yet, not all calls to `getLanguageIRI` check first --and might as well implement in the getter.  Adding the fallback logic would align with gracefully continuing when we can: the show must go on!

**Comment by clarkepeterf** [comment]
@brent-hartwig @azaroth42 

There are ways I can dynamically generate a list of Identifiers for languages, but if we are generating identifiers at build time, this means we are still dependent on running an extra build step like `generateDataConstants` after a data load. Can I hard-code identifiers (Getty AATs or similar 3rd party identifiers) for the current list of 811 language data constants in DEV? Or some subset of them?

Current list of languages attached 
[langlist.json](https://github.com/user-attachments/files/17103297/langlist.json)

@brent-hartwig yes Ideally I would hard-code in the current identifiers and we can use English as a backup

**Comment by clarkepeterf** [comment]
I inserted the language aats into the identifier constants

**Comment by roamye** [comment]
Approved by UAT

**Comment by brent-hartwig** [comment]
@clarkepeterf, it looks like something got past us, leading to the name profile requests returning the entire document:

```
2024-10-11 13:40:03.432 Warning: Unable to apply the 'name' profile. Returning entire document. Cause: IDENTIFIERS.hasIdentifier is not a function
2024-10-11 13:40:03.448 Warning: Unable to apply the 'name' profile. Returning entire document. Cause: IDENTIFIERS.hasIdentifier is not a function
```

Looks like `IDENTIFIERS.` needs to be dropped from `IDENTIFIERS.hasIdentifier(key)` in:

```javascript
function getLanguageIdentifier(languageCode) {
  const key = _getLanguageIdentifierKey(languageCode);
  if (IDENTIFIERS.hasIdentifier(key)) {
    return IDENTIFIERS[key];
  }
  throw new InternalServerError(
    "A language identifier is not defined for the '" +
      languageCode +
      "' language code. Developer to correct the reference or ensure the identifier is defined."
  );
}
```

**Comment by brent-hartwig** [comment]
@clarkepeterf, I encountered a second issue: `IDENTIFIERS.primaryName`'s value is HTTPS but the data uses HTTP.

`cts.estimate(cts.jsonPropertyValueQuery('id', 'http://vocab.getty.edu/aat/300404670', ['exact']))`
--> 41890461

`cts.estimate(cts.jsonPropertyValueQuery('id', 'https://vocab.getty.edu/aat/300404670', ['exact']))`
--> 0

This appears to be the only one in IDENTIFIERS that uses HTTPS.
