### ISSUE TITLE
Document all in-use Gradle properties (from 45)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#3]
Source: all gradle*.properties files plus build.gradle.

Consider adding it within a) "Gradle Properties" section of /docs/lux-backend-deployment.md, b) lux-backend-build-tool-and-tasks.md, or c) a new file dedicated to the Gradle properties.

Related links: #1071

**Comment by brent-hartwig** [comment]
Propose closing.  We've done a pretty good job documenting custom properties directly within the properties files and a code and configuration search for a specific property or `%%` yields purposes pretty quickly.
