### ISSUE TITLE
Fix Incorrectly Configured Fields - idIndexReferences

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#301]
**Problem Description:**
Per [this comment](https://github.com/project-lux/lux-marklogic/issues/74#issuecomment-2310901592)

Some search terms have their `idIndexReferences` property incorrectly configured as an array. This is not causing any functional problems right now, but has potential to in the future.

**Expected Behavior/Solution:**

the `idIndexReferences` for the search terms mentioned in [this comment](https://github.com/project-lux/lux-marklogic/issues/74#issuecomment-2310901592) should be changed to be an array.

The app should continue to function as expected.

~~**Requirements:**~~

~~**Needed for promotion:**~~

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- Internal testing only - no UAT 

~~**Dependencies/Blocks:**~~

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
~~- Blocking: Issues being blocked by the completion of the current issue.~~

**Related Github Issues:**

-https://github.com/project-lux/lux-marklogic/issues/74

~~**Related links:**~~

~~**Wireframe/Mockup:**~~

**Comment by jffcamp** [comment]
Ah, so amongst other things, this will be good to do before the next dataset.

**Comment by roamye** [comment]
@clarkepeterf - once this is in PROD, who would be best to review that the idIndexReferences are an array?

**Comment by roamye** [comment]
Approved by UAT 9/27, but please see comment above.

**Comment by clarkepeterf** [comment]
@roamye The fields have all been updated such that their `idIndexReferences` property is an array. See here:

![Screenshot 2024-10-07 at 10 14 28 AM](https://github.com/user-attachments/assets/377ba9d8-78b9-475b-8a7f-bf9d2fc5c675)

**Comment by roamye** [comment]
perfect. closing this :)
