### ISSUE TITLE
Update Search Terms For Triples Affected By <recordType>Influenced<activityType> Data Change

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#309]
**Problem Description:**
https://github.com/project-lux/data-pipeline/issues/112 Updated the triples from `influenced_by_<recordType>` to `<recordType>Influenced<activityType>`
**Expected Behavior/Solution:**
Update triples to match data

~~**Requirements:**~~
~~List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.~~

~~**Needed for promotion:**~~
~~If an item on the list is not needed, it should be crossed off but not removed.~~

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- TST: https://lux-front-tst.collections.yale.edu/view/person/165a61ff-8455-4a04-9505-bb8e37a149c3 No longer shows "exhibitions" in the Related People & Groups dropdown - this is good
- PRD: https://lux.collections.yale.edu/view/person/165a61ff-8455-4a04-9505-bb8e37a149c3 Shows "exhibitions" in the Related People & Groups dropdown - this is wrong

~~**Dependencies/Blocks:**~~

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
~~- Blocking: Issues being blocked by the completion of the current issue.~~

**Related Github Issues:**
  - https://github.com/project-lux/lux-marklogic/issues/233
  - https://github.com/project-lux/data-pipeline/issues/112

~~**Related links:**~~

~~- These links can consist of resources, bugherds, etc.~~

~~**Wireframe/Mockup:**~~
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by roamye** [comment]
@clarkepeterf - does the UAT example mean I will not see the relationship label "exhibitions" or that I will not see types of exhibitions? If it is the second one can you point out one that currently shows in PRD but not tst?

**Comment by clarkepeterf** [comment]
@roamye correct you should NOT see it "exhibitions" under Related People & Groups for that link in TST. If you remove the `-front-tst` from the URL you will see the PRD URL which does have "exhibitions" (which is wrong, so it's fixed in TST)

**Comment by clarkepeterf** [comment]
@roamye I also just updated the UAT to have a PRD link

**Comment by roamye** [comment]
Approved by UAT 9/12

**Comment by roamye** [comment]
Looks good in PROD. Closing.
