### ISSUE TITLE
Create checklist-style procedures of frequent activities (from 901)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#31]
I would like to make sure that the most common activities are clearly documented and up to date.
Multiple people on my team need to be able to execute the necessary sequential steps to:

- Reload data
- Update indexes
- Deploy middle-tier
- Deploy backend
- Deploy frontend
- Test new dataset
  - tests prior to load
  - tests post load
- etc.

Ideally w/out having frequent practice. We still seem to be in a situation where there are steps being missed. If this is because we aren't following the existing documentation, and it is good enough, then it is simply a training issue.

**Comment by brent-hartwig** [comment]
I'm going to presume we're beyond this and am closing.  We can open new tickets for specific documentation requests.
