### ISSUE TITLE
Create User and Deploy Middle Tier for IPCH Portal

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#314]
**Problem Description:**
IPCH is interested in a portal for LML

**Expected Behavior/Solution:**
Create a portal for LML

**Requirements:**
- [x] Create roles and deploy - done with https://github.com/project-lux/lux-marklogic/issues/280
- [x] Create users for tenant(s) that wish to host this portal
- [x] Deploy byunit1 middle tier using above user's credentials

~~**Needed for promotion:**~~
~~If an item on the list is not needed, it should be crossed off but not removed.~~

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- https://lux-byunit1.collections.yale.edu/ only contains content from IPCH (currently just LML - Lens Media Lab)

~~**Dependencies/Blocks:**~~

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
~~- Blocking: Issues being blocked by the completion of the current issue.~~

**Related Github Issues:**
- https://github.com/project-lux/lux-marklogic/issues/280
~~**Related links:**~~

~~- These links can consist of resources, bugherds, etc.~~

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by clarkepeterf** [comment]
implemented via https://github.com/project-lux/lux-marklogic/pull/321 and https://git.yale.edu/lux-its/ml-cluster-formation/pull/54

**Comment by roamye** [comment]
@clarkepeterf - is there an example of a search that should show up within this IPCH portal? I couldn't find one, but I am also unsure what searches are classified as IPCH.

**Comment by clarkepeterf** [comment]
@roamye Here are a couple of searches with results:

https://lux-byunit1.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22blue%22%2C%22_lang%22%3A%22en%22%7D&sq=blue
https://lux-byunit1.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22paper%22%2C%22_lang%22%3A%22en%22%7D&sq=paper

**Comment by clarkepeterf** [comment]
Also, all items in this tenant are from LML (Lens Media Lab) - which is part of IPCH

**Comment by roamye** [comment]
Approved by UAT 9/27

**Comment by roamye** [comment]
Closing as this was implemented.
