### ISSUE TITLE
Update AAT for Archive Sorting

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#325]
**Problem Description:**
The AAT used for archive sorting is being updated to a more appropriate value.

The current AAT is for sort titles (http://vocab.getty.edu/aat/300451544)
The new AAT is for sort values (http://vocab.getty.edu/aat/300456575)

When the data changes to use the new AAT, our indexes need to update to match the data, otherwise archive sorting will break.

This affects the following indexes:
- workArchiveSortId
- itemArchiveSortId

**Expected Behavior/Solution:**
Archival sorting continues to work as normal even after the AATs are updated

The affected indexes (workArchiveSortId and itemArchiveSortId) are updated to match the new AATs in the data. (new AAT = http://vocab.getty.edu/aat/300456575)

~~**Requirements:**~~
~~List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.~~

~~**Needed for promotion:**~~
~~If an item on the list is not needed, it should be crossed off but not removed.~~

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

Not really a testable change. Archive sorting should continue to function as normal. If we don't update the AATs it will break.

**Dependencies/Blocks:**

- Blocked By: New Dataset @kkdavis14 please let me know when we have a new dataset containing the updated AATs.
~~- Blocking: Issues being blocked by the completion of the current issue.~~

~~**Related Github Issues:**~~

~~- Issues that contain similar work but are not blocking or being blocked by the current issue.~~

~~**Related links:**~~

~~- These links can consist of resources, bugherds, etc.~~

~~**Wireframe/Mockup:**~~
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by clarkepeterf** [comment]
@roamye I am adding this issue to prioritization review. It is waiting on an update to the data. @kkdavis14  will let me know when the new data is ready. This will be a critical change when the data is updated so that archive sort can keep working.

It is a quick change. I would propose to put this item in backlog. I can pull it in and get it done quickly when the data is ready.

**Comment by roamye** [comment]
UAT 9/27: 
- relies on units making a change. (only for YUL - archives) 
- - this data should come in with their next update.

**Comment by kkdavis14** [comment]
@clarkepeterf this is fixed in current SBX data that is likely to be promoted.

**Comment by roamye** [comment]
@kkdavis14 - is there an example for this issue? / can you confirm this is working as expected? 

cc: @clarkepeterf

**Comment by kkdavis14** [comment]
https://github.com/project-lux/lux-frontend/issues/411#issuecomment-2427676720
@roamye as per Peter's comment, PRD won't be fixed til indexes updated in next Blue/Green switch (10/28).
all lower environments fixed.

**Comment by clarkepeterf** [comment]
You can see the fix here:
- https://lux.collections.yale.edu/view/set/7b2c542b-5741-43d0-a4ea-cc288b279447
  - PRD items are out of order (after FHS/3/1 - 1, 10, 100)
- https://lux-front-tst.collections.yale.edu/view/set/7b2c542b-5741-43d0-a4ea-cc288b279447
  - TST items are in order (after FHS/3/1 - 1, 2, 3)

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in PROD closing.
