### ISSUE TITLE
Related lists stats script

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#329]
Just adding a script that can return stats for deployed related lists configuration.  This script may be executed manually via QC and is not part of the runtime app.  UAT not required.

```javascript
/*
 * Use this script to get stats from the deployed related lists configuration.
 * Set the database to LUX's content database and execute.  The script does
 * not require any configuration.  Output includes a) number of related lists,
 * b) triple search counts for all related lists, at the search scope level,
 * and for each related list, and c) number of related lists per search scope.
 */
...
```

**Comment by roamye** [comment]
UAT was not required for this ticket, Can one of you confirm this is OK to close as it is in PROD? @clarkepeterf @brent-hartwig

**Comment by clarkepeterf** [comment]
@roamye Ok to close. This is a script in our repo that can be run by developers. Not part of the LUX application.

**Comment by roamye** [comment]
Thanks @clarkepeterf. Closing.
