### ISSUE TITLE
Set Classification Triple Workaround

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#337]
**Problem Description:**
Collection sets do not have the `setClassifiedAs` triple in the 2024-09-19 dataset

**Expected Behavior/Solution:**
Use `referenceClassifiedAs` instead of `setClassifiedAs` for  ML v1.26.0. When a new dataset fixes this issue, we will revert the using `setClassifiedAs`

~~**Requirements:**~~
~~List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.~~

~~**Needed for promotion:**~~
~~If an item on the list is not needed, it should be crossed off but not removed.~~

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- LUX continues to work as normal

~~**Dependencies/Blocks:**~~

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
~~- Blocking: Issues being blocked by the completion of the current issue.~~

~~**Related Github Issues:**~~

~~- Issues that contain similar work but are not blocking or being blocked by the current issue.~~

~~**Related links:**~~

~~- These links can consist of resources, bugherds, etc.~~

~~**Wireframe/Mockup:**~~
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Unreviewable and in PROD. Closing

**Comment by clarkepeterf** [comment]
Triple was reverted in PR https://github.com/project-lux/lux-marklogic/pull/358
