### ISSUE TITLE
Create Non Semantic Sort Options across all tab scopes. 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-marklogic#342]
**Problem Description:**
The front end would like to implement new non-semantic sort options to its sort toggle. 
This issue will support the creation of each new sort. 

**Expected Behavior/Solution:**
Non-semantic sort options will appear on all sort toggles across tab scopes. 

**Requirements:**
Create a sort to allow scope tabs to sort records by the sort options below in both ascending and descending order:
Objects: 
- Has Digital Image
- Object Class

Works: 
- Has Digital Image
- Work Class
People/Orgs: 
- Has Digital Image (tab sort and results sort) 
- Person/Group Class

Places: 
- By Latitude
- By Longitude
- Has Digital Image (tab sort and results sort) 
- Has Map Coordinates

Concepts: 
- Concept Class

Events: 
- Event Class
- ~~Has Digital Image (tab sort and results sort)~~

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- See FE issue: https://github.com/project-lux/lux-frontend/issues/396

**Dependencies/Blocks:**
- Blocking: https://github.com/project-lux/lux-frontend/issues/396

**Related Github Issues:**
N/A

**Related links:**
- Sorting (order); https://docs.google.com/spreadsheets/d/1c9kqnSqTVSGSlV4FkX0wXRphwTYlbHuApP500QtQzGU/edit?gid=0#gid=0

**Wireframe/Mockup:**
~Place wireframe/mockup for the proposed solution at end of ticket.~

**Comment by prowns** [comment]
Performance tests not needed, per 11/15 discussion.

**Comment by clarkepeterf** [comment]
### Objects
| UI Label | Sort Name |
|----------|-----------|
|Has Digital Image| |
|Object Class| |

### Works
| UI Label | Sort Name |
|----------|-----------|
|Has Digital Image| |
|Work Class| |

### People/Orgs
| UI Label | Sort Name |
|----------|-----------|
|Has Digital Image| |
|Person/Group Class| |

### Places
| UI Label | Sort Name |
|----------|-----------|
|By Latitude| https://github.com/project-lux/lux-marklogic/issues/391 |
|By Longitude| https://github.com/project-lux/lux-marklogic/issues/391 |
|Has Digital Image| |
|Has Map Coordinates| https://github.com/project-lux/lux-marklogic/issues/391 |

### Concepts
| UI Label | Sort Name |
|----------|-----------|
|Concept Class| |

### Events
| UI Label | Sort Name |
|----------|-----------|
|Event Class| |
|Has Digital Image| |

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Closing looks good in PROD. 

Note: lattitude/longtitude/has map is not currently available but will be created through: https://github.com/project-lux/lux-marklogic/issues/391
