### ISSUE TITLE
Provide Flux-compatible transform

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#351]
Flux requires transforms to be deployed as a [MarkLogic REST transform](https://docs.marklogic.com/guide/rest-dev/transforms), which gets deployed a bit different than how we have been deploying the transform used by MLCP.  With the former, one only gets to specify the function name.  With the latter, one could also specify the module the function is defined in.  Further, the transform signature is different.

We have the option to refactor the transform function into a library and support both entry points.  Not deemed required for our initial round of Flux testing as the changes can be made to a branch and not yet folded into a release branch.

Permission granted by Jeff on 16 Oct to bypass the standard process and go straight into development.  Set milestone to 4 Nov.

Marked as blocking since we cannot conclude whether Flux can replace MLCP until it can do everything we're using MLCP to do, including this transform.  The take-Flux-for-a-spin ticket is https://git.yale.edu/lux-its/datatransfer/issues/54.

**Comment by roamye** [comment]
@brent-hartwig - this is unreviewable correct? also wondering if it is still in progress.

**Comment by brent-hartwig** [comment]
Hi, @roamye.  We can close this one.  We should do #368 instead.  Explanation provided in that ticket.

**Comment by roamye** [comment]
Approved by UAT to close.
