### ISSUE TITLE
Semantic facet optimization idea: registered queries and possibly cache warming

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#362]
> [!NOTE]
> #365 is a **MUCH** better optimization than this one.  It's faster and doesn't have this one's implementation complexities (listed below).  This one should be closed.

**Problem Description:**
Semantic facet requests can timeout, even after the 59 seconds they are allotted.  Unknown how likely users would use these facets should they take more than _n_ seconds to appear.

An extreme example takes no less than 4.4 minutes: the responsible collections facet for an estimated 15 million items curated by Yale University Library (YUL) --a boil the ocean search that LUX is asked to calculate facets for.  Using the techniques described below, this facet request completed in 10 seconds.

In addition to wanting to reduce semantic facet calculation times, we should take into consideration:

1. Implementation complexity.  As the following section details, there are complexities.
2. Optic API.  The above example is query 17 in the Optic/CTS comparison.  We or Engineering may find a faster way to calculate these facets using Optic.
3. Typical request durations.  How long do semantic facet requests take on average?  Are they only excessively slow for boil-the-ocean searches?  Do caches above the middle tier offset this enough?

Even if the above factors prevent this ticket from moving forward, I wanted to document the findings and techniques.

**Expected Behavior/Solution:**
The above result required a registered query and warm caches.  Unless immediately after MarkLogic restarts, caches will be warm.  They will not necessarily have all the values required by the semantic facet requests, but would have some.  Thus, of the contributing factors, the registered query is most important and could provide benefits on its own.  Nonetheless, here's the complete list with implementation options.

_Registered Queries_

We could register a static portion of the semantic facet query.  It appears we only need one for the responsible collection query.  I haven't looked at the other semantic facet.

Responsible collections queries:
[register-query.js.txt](https://github.com/user-attachments/files/17525690/register-query.js.txt)
[use-registered-query.js.txt](https://github.com/user-attachments/files/17525691/use-registered-query.js.txt)

Implementation complexities:

1. Registered queries do not survive a restart and can age out of its cache when the cache has reached it size limit.  We would need a way to automatically re-register queries.  A technique is to register immediately before use, which is practically instantaneous so long as the query does not include an expensive call to cts.triples, such as our semantic facet queries do.  Worst case, we can wrap uses of registered queries within try/catch and have the task server re-register the associated query; that wouldn't help the current request and thus we should continue thinking about other ways, such as a scheduled task.
2. To use a registered query, one needs its ID.  The ID is returned when registering the query.  Some get away with cts.registeredQuery(cts.register(query)) as the same query returns the same hash/ID; but as noted above, we cannot in the semantic facet context.  As such, we would need a way to maintain a list of registered query IDs.

_Caches_

The term list and triple caches are most relevant for at least the responsible collections facet, and likely the responsible units facet as well.  As noted above, these caches will typically be warm but not necessarily have as many values needed by these facets as our performance objective needs.  If that turns out to be the case, we could explore options to keep more of those values in the caches.  A technique is to use a scheduled task, configured to run as frequently as needed.

Here's an example for the triple caches that is based on a collection query.

```javascript
xquery version "1.0-ml";
let $log := xdmp:log("Warming triple caches", "info")
let $cq := cts:collection-query(("AcmeCarrierClaim", "AcmeProvider", "AcmeMember"))
let $uris := cts:uris((), ("sample=1000", "score-random"), $cq)
return cts:triples((), (), (), (), (), cts:document-query($uris))
```

**Requirements:**
List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~- [ ] Wireframe/Mockup - Mike~
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Middle tier requirements - TBD
- [x] Frontend requirements - None
- [ ] Compels a performance test?
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**

- These links can consist of resources, bugherds, etc.

**Wireframe/Mockup:**

N/A

**Comment by brent-hartwig** [comment]
Propose close: #365 is a MUCH better optimization than this one. It's faster and doesn't have this one's implementation complexities (listed above).

**Comment by roamye** [comment]
UAT Approved to close.
