### ISSUE TITLE
LUX Fronts Next Steps: Backend Usage Insights (from 1078)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#39]
**Problem Description:**
The [log analysis scripts](https://git.yale.edu/lux-its/marklogic/tree/v1.1.0/scripts/logAnalysis) produce TXT, JSON, and TSV files of Marklogic Logs.  Manually, TSV files are then saved as a spreadsheet and formatted.  All charts are manually created.  [#1002](https://git.yale.edu/lux-its/marklogic/issues/1002) recommends seeking out a more polished solution that would enable the team to gain insights more efficiently. (Currently Closed) 

 For instance, some such products would enable one to change the period and have all visuals immediately updated.  This project’s scripts would have to be rerun and visuals recreated, manually.  Start by finding out how far AWS can get us.
The scope is limited to MarkLogic cluster usage. 

**Expected Behavior/Solution:**
Solution is to use AWS Cloud Watch to Log Insights to cut the manual process of creating these visuals, as well as showing these visuals on a browser/dashboard. 

**Requirements:**
- Propose a a feasible solution from AWS that can cut the manual process. 
- testing is done via AWS CludWatch Dashboards.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ticket clarification 
- [ ] next steps identified
- [ ] decision
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- what is scope/problem and solution?
- how is it tested?
- examples?

**UAT/LUX Examples:**

- Examples can be found in the comment below: [here](https://github.com/project-lux/lux-marklogic/issues/39#issuecomment-2243371517)
-  https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards/dashboard/LUX (aws access needed) 

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
- Old Github Tix: https://git.yale.edu/lux-its/marklogic/issues/1078 

**Related links:**
N/A

~**Wireframe/Mockup:**~
Old: 

Updated: 
CPU and network utilization: 
![image](https://github.com/user-attachments/assets/99d4bdd4-b697-4fc9-aa8a-5b4006e90f6c)
MarkLogic app server errors:
![image](https://github.com/user-attachments/assets/e31ce1e3-2739-410b-808b-857fd510272e)
LUX top 10 long queries:
![image](https://github.com/user-attachments/assets/cf8eafe9-b235-4f6a-84fd-fb3541ea95fc)
Hourly request count: 
![image](https://github.com/user-attachments/assets/f5f85994-1588-43d0-8115-e75d9aee981c)

**Comment by roamye** [comment]
@gigamorph & @xinjianguo - 

From the old ticket ( https://git.yale.edu/lux-its/marklogic/issues/1078 ) it looks like this ticket should be in the 'In Progress' status once it answers the questions of: 

- what is scope/problem and solution
- how is it tested?
- examples?

I can format the ticket, but which one of you would be able to provide the information to move this ticket forward?

**Comment by roamye** [comment]
@xinjianguo - from the 7/3 ticket forming meeting it was noted that you will be the one to provide more information as you worked on this ticket.

**Comment by xinjianguo** [comment]
@roamye OK let me try to answer these questions:

- what is scope/problem and solution

The scope is limited to MarkLogic cluster usage. Solution is to use AWS CludWatch, Logs Insights.

- how is it tested?

It is tested via AWS CludWatch Dashboards.

- examples?

Some example screen shots as follow:

CPU and network utilization
![Image](https://github.com/user-attachments/assets/bd497ae1-709d-4771-b5c5-b84070799af4)

MarkLogic app server errors

![Image](https://github.com/user-attachments/assets/6c7f1d56-0236-4ffc-a1ab-b38e4aa2174c)

LUX top 10 long queries

![Image](https://github.com/user-attachments/assets/9f045051-a67c-41fb-a02b-03f6a83fc319)

Hourly requests count

![Image](https://github.com/user-attachments/assets/d9c448da-c370-46d6-9504-070dbecfd2c1)

**Comment by roamye** [comment]
From conversation 10/9 with @xinjianguo - this ticket is already done. Propose close.
