### ISSUE TITLE
Update agentOccupationId Field to also map to Role (from 1092)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#40]
**Problem Description:**
Some records for agents are classified as a type called "Role" this is a distinct classification from "Occupation", but they are used interchangeably. Currently there is a field for "Occupation" but not for "Role". We would like to update the agentOccupationId Field to also contain a path for "Role" and include a label change to `Occupation/Role`.

**Expected Behavior/Solution:**
Update the `agentOccupationID` field to contain a path for Role and re-label `Occupation` to `Occupation/Role` in the Advanced Search with new Help Text. 

**Requirements:**
The update `agentOccupationID` which includes the single field `Occupation` in Advanced Search will..
- contain a path for Role searches to modify the  `Role` searches in person and group facets/records and accordion `People and Groups with Occupation/Role` 
- The Advanced Search label `Occupation` will be renamed to `Occupation/Role`
- Advanced Search Help text will need to be updated: 
      - Search for a People & Groups with the specified Occupation or Role. (TBD on approval) 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- This search matches Steve Jobs for occupation "Chief Executive Officer" when that is classified as a "Role" in his document.
https://lux-front-dev.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22steve%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22jobs%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22occupation%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F0243a4ef-fa6f-4f52-9fb5-57b730ba4880%22%7D%7D%5D%7D

**Dependencies/Blocks:**
Prerequisites: [x] Create a pipeline data constant for Role. - https://git.yale.edu/LUX/pipeline/issues/505

Blocking: 
-  https://git.yale.edu/lux-its/lux-web/issues/1844 (old repo) |  https://github.com/project-lux/lux-frontend/issues/45

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**
Based on [Bugherd #1744](https://www.bugherd.com/projects/284041/tasks/1744)

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by roamye** [comment]
@clarkepeterf - the prerequiste for this ticket has been complete as https://git.yale.edu/LUX/pipeline/issues/505 is closed. 
Is this OK to add onto 7/22 milestone? or does this need to be pushed further out?

**Comment by clarkepeterf** [comment]
@roamye I think it should be good to go, I just need one bit of information - @kkdavis14 can you tell me what AATis used when an agent is classified as a Role?

**Comment by kkdavis14** [comment]
@clarkepeterf 300435108

**Comment by clarkepeterf** [comment]
@kkdavis14 do we have an example of a record where a person/group has a Role? I want to test it's showing up correctly in DEV now

**Comment by kkdavis14** [comment]
@clarkepeterf https://lux-front-dev.collections.yale.edu/view/person/c225d5e4-8767-4a25-802b-af054d5e8f52 LGTM.

**Comment by roamye** [comment]
7/22 dev meeting: 
Index was deployed on 7/22 release. This ticket will need to be re-formatted to include the label change which will go out on the 08/05 release.

**Comment by roamye** [comment]
Approved by UAT 8/7

**Comment by roamye** [comment]
Looks good in PROD. Closing.
