### ISSUE TITLE
Fix Returning Dates For Facets (from 1102)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#43]
**Problem Description:**
If you use date facets, it's possible to get a list of years that ends earlier. Facets only returns start dates.  

**Expected Behavior/Solution:**
Return start dates and end dates for improved accuracy in results
Note: will also need to add new index field for all dates, right now they only have begin string, not end string

**Requirements:**
List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [x] Confirm that it is feasible to return both sets of values - Peter
- [ ] Document changes that need to be made in the ticket - Peter
- [x] Corresponding front-end ticket (to handle the extra dates) - Kameryn
- [ ] Examples for testing (see 1878)
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**
- https://github.com/project-lux/lux-marklogic/issues/256
- https://github.com/project-lux/lux-marklogic/issues/37
- ~THIS TICKET MUST BE DEPLOYED WITH #https://github.com/project-lux/lux-frontend/issues/54~ No longer necessary as this ticket will be closed. 
- Old tix of 54: https://git.yale.edu/lux-its/lux-web/issues/1878

**Related links:**
N/A

**Wireframe/Mockup:**
N/A

**Comment by brent-hartwig** [comment]
### This Ticket

> Facets only returns start dates.

Very true.  We could address this by:

1. Identify the end dates and ensure their string values are indexed.
2. Modify facetConfig.mjs to support multiple indexes per facet, whether as a single or second property.  In other contexts, we renamed the `indexReference` string property to the `indexReferences` string array property yet the next item may encourage we go with a second property instead.
3. If necessary, update generateRemainingSearchTerms.mjs' use of facetConfig.mjs.
4. Update facetLib.mjs' call to cts.fieldValues to use all indexes associated with a facet.

### Optimization

_Whether as part of this ticket's scope or another..._

Thinking about the above has led to an optimization idea as well.  If the frontend only needs the first and last dates, the facets endpoint could offer a parameter saying as much, yet not be limited to dates.  The following illustrates what the implementation could look like where `q` would be the search query.

```
const q = cts.documentQuery([
  'https://lux.collections.yale.edu/data/person/098de228-41f2-404e-83e2-e48b2bd632f8'
]);
const fields = ['agentBornStartDateStr', 'agentDiedStartDateStr'];
const baseOptions = ['limit=1', 'score-zero', 'lazy'];
const results = {
  earliest: cts.fieldValues(fields, null, baseOptions.concat(['ascending']), q),
  latest: cts.fieldValues(fields, null, baseOptions.concat(['descending']), q),
};
results;
```

If we didn't want the endpoint consumer to control this behavior, we could extend the facet configuration.  My preference is a new endpoint parameter that defaults to returning the first and last values for date facets.  Here is how the remaining search terms generator already identifies date facets: `const isDate = facetIndexReference.endsWith('DateStr')`.  If we add a parameter, it should be documented in the API usage doc.

I would expect the facet to be calculated faster and, for some searches, a _much_ smaller response size.

cc: @clarkepeterf

**Comment by brent-hartwig** [comment]
@clarkepeterf, please review the above suggestion in the context of #256.

**Comment by roamye** [comment]
From ITS Team Meeting 8/23: 
- this is not blocked or dependent by FE 37. 
- this issue could go out but if 37 is not deployed it may have some errors.

**Comment by roamye** [comment]
Approved by UAT 9/12 to close
