### ISSUE TITLE
Estimate counts must match result counts when searching/faceting by date (from 1129)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#47]
**Problem Description:**
While testing the deployment of these tickets:
[Update the advanced search date inputs and help text for date inputs #1878](https://git.yale.edu/lux-its/lux-web/issues/1878)
[Update date facets to reflect recent ML change #2007](https://git.yale.edu/lux-its/lux-web/issues/2007)
[Issue With Date Facets #1032](https://git.yale.edu/lux-its/marklogic/issues/1032)
It was observed that the result count was correct BUT the estimate count on the results tab was sometimes incorrect. Likely due to the estimate count being unfiltered.

**Expected Behavior/Solution:**
The estimate count displayed on the tab should match the count in the result list. This should occur whether a user is performing an advanced search or is using the facets to filter by date range.

**Requirements:**
List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Heather~
- [ ] ~Committee discussions - Sarah~
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- The problem is [demonstrated by this query](https://lux-front-dev.collections.yale.edu/view/results/objects?q=%7B%22producedDate%22%3A%7B%22start%22%3A%222023%22%2C%22end%22%3A%222023%22%7D%7D), when the new date code is used. 

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking:
- https://github.com/project-lux/lux-frontend/issues/76 
-- [Update the advanced search date inputs and help text for date inputs #1878](https://git.yale.edu/lux-its/lux-web/issues/1878)
-- [Update date facets to reflect recent ML change #2007](https://git.yale.edu/lux-its/lux-web/issues/2007)
-- [Issue With Date Facets #1032](https://git.yale.edu/lux-its/marklogic/issues/1032)

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**

- [Teams chat](https://teams.microsoft.com/l/message/19:GmLeQu1cBR40mfrno-l8lngg7RFCcJs8fvFIw-MJjIM1@thread.tacv2/1704903709680?tenantId=dd8cbebb-2139-4df8-b411-4e3e87abeb5c&groupId=4620eac6-0955-4c69-93e8-b493b21f0df6&parentMessageId=1704903709680&teamName=MarkLogic&channelName=General&createdTime=1704903709680)
- Bugherd: https://www.bugherd.com/projects/284041/tasks/1931

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by brent-hartwig** [comment]
I'm witnessing multiple oddities with the date search pattern and suggest its related ticket (#37) before this one.

**Comment by brent-hartwig** [comment]
> The estimate count displayed on the tab should match the count in the result list. This should occur whether a user is performing an advanced search or is using the facets to filter by date range.

@jffcamp and @prowns, I'd like to reiterate my comment on #37: the expected behavior is not always achievable at scale. Facets and estimates are calculated on unfiltered results --results determined via indexes alone. We can investigate specific instances but need to reset expectations. Investigating specific instances may surface a bug or means to index the data better, but this will not be true in all cases.

For this particular ticket, I vote to retest after everything uncovered by #37's investigation is addressed.

**Comment by clarkepeterf** [comment]
This was due to a change that was backed out. If we decide to make a change like this in the future we will have to keep this in mind

**Comment by roamye** [comment]
Approved by UAT 9/12 to close.
