### ISSUE TITLE
Has Digital Image facet does not add up to total results for works (from 1147)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#52]
**Problem Description:**
Has Digital Image facet does not add up to total results for works
**Expected Behavior/Solution:**
The sum of Yes counts and No counts for Has Digital Image facet should add up to the total number of results
**Requirements:**
The sum of Yes counts and No counts for Has Digital Image facet should add up to the total number of results

This has to do with the fact that Works can return Sets, but the index for `workHasDigitalImageBoolean` does not account for Sets.

The same is true for `workIsOnlineBoolean`

The index will need to be updated with an xpath that accounts for Sets

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Heather~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

This link - https://lux-front-tst.collections.yale.edu/view/results/works?facetRequest=true&pf=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A1%7D%5D%7D&pp=1&q=%7B%22text%22%3A%22sun%22%2C%22_lang%22%3A%22en%22%7D&sq=sun - should have Has Digital Image counts for Yes and No that add up to the total results

~~**Dependencies/Blocks:**~~

~~**Related Github Issues:**~~

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/1969
**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by roamye** [comment]
Approved by UAT 7/22

Note: new ticket will have to be created as the Is Online facet does not add up.

**Comment by roamye** [comment]
Looks good in PROD. Closing.
