### ISSUE TITLE
Research on estimate issues for hyphen "-"  (from 1154)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#53]
**Problem Description:**
When using a hyphen "-" within the search "(stieglitz OR o'keeffe) -library" the facets "Campus Division" still shows Yale University Library. This campus division shows 991 results but upon clicking there are 0 results displayed. 

**Expected Behavior/Solution:**
Campus division "Yale University Library" should display 0 results or not display "Yale University Library" as the hyphen "-" excludes the term Library.  Research will need to be done as this is an estimates issue. 

**Requirements:**
- When a user enters a search result without the hyphen "-" it will display all results for the search. 
- All facets will have correct estimates. 
- When a user enters a search result that contains the hyphen "-" then all search results will display correct estimates that exclude the term after the hyphen. 
- All facets will have correct estimates for the excluded search results. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike 
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
What it looks like [now](https://lux-front-tst.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22text%22%3A%22stieglitz%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D%5D%7D%2C%7B%22NOT%22%3A%5B%7B%22text%22%3A%22library%22%2C%22_lang%22%3A%22en%22%7D%5D%7D%5D%7D&sq=%28stieglitz+OR+o%27keeffe%29+-library&ip=1&facetRequest=true&if=%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fgroup%2Fd07b9b86-0a1e-4026-aa4c-8ecba8bbd9c9%22%7D%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fgroup%2Fd07b9b86-0a1e-4026-aa4c-8ecba8bbd9c9%22%7D%7D%7D%5D%7D%5D%7D): 
![image](https://github.com/project-lux/lux-marklogic/assets/160149818/e8098dc9-7029-4956-a0d5-0bc92bd93d19)

What it should look like: 
TBD based on research information. 

**Dependencies/Blocks:**.

**Related Github Issues:**

**Related links:**
- [Location in LUX](https://lux-front-tst.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22text%22%3A%22stieglitz%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D%5D%7D%2C%7B%22NOT%22%3A%5B%7B%22text%22%3A%22library%22%2C%22_lang%22%3A%22en%22%7D%5D%7D%5D%7D&sq=%28stieglitz+OR+o%27keeffe%29+-library&ip=1&facetRequest=true)
- https://www.bugherd.com/projects/284041/tasks/1950

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by brent-hartwig** [comment]
@roamye and @prowns, perhaps this issue has been addressed.  The following screenshot was taken of production today.

![image](https://github.com/project-lux/lux-marklogic/assets/13734146/8d7b23a4-3efb-4635-85ee-380d22435ea9)

Blue is production today.  Associated versions:

- Frontend v1.25.2
- Middle tier v1.1.8
- Backend v1.15.0
- MarkLogic v11.0.3 (with ML 11.2 nightly build remnants)
- Dataset 2024-04-18

**Comment by prowns** [comment]
Thanks @brent-hartwig - that is promising.  Will review with a propose-close.

**Comment by roamye** [comment]
per UAT closing
