### ISSUE TITLE
Data Constant Issue for Item Type Icons (from 1175)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#55]
**Problem Description:**
The frontend wants to add icons for different item types. We need a list of AATs for Item Type to identify which icons should be used.  

May be affect by our new way of handling data constants:
#54 

**Expected Behavior/Solution:**
Data constant is created for new Item Types.

**Requirements/UAT Links:**
From the AAT values , Icons will match to the correct Item Types and
When the ticket is complete, data constants will exist for the following types: 

UAT Links
[Collections](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D&sq=o%27keeffe&ip=1&facetRequest=true&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F6e1b1bbc-d691-4f7c-8cf1-bb48ee2034a2%22%7D%7D%5D%7D)
[Software & Electronic Media](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22data%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22set%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=data+set&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2Fec279104-cf49-4c00-8dd8-caa5f307d777%22%7D%7D%5D%7D&facetRequest=true)
[Textual Works](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D&sq=o%27keeffe&ip=1&facetRequest=true&if=%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F5162b925-3d52-4d50-928c-0594851308d9%22%7D%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F5162b925-3d52-4d50-928c-0594851308d9%22%7D%7D%7D%5D%7D%5D%7D)
[Scores and Notation](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22music%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22score%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=music+score&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F553abb46-340c-46b0-9a19-aa9eb912db78%22%7D%7D%5D%7D&facetRequest=true)
[Object Record](https://lux.collections.yale.edu/view/object/21f8cdf3-24ba-4a85-a0ad-7d030eb84550)
[Cartography](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22map%22%2C%22_lang%22%3A%22en%22%7D&sq=map&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F6e901924-9ff3-4056-a1ce-71dce5424b33%22%7D%7D%5D%7D&facetRequest=true)
[Numismatics](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22coin%22%2C%22_lang%22%3A%22en%22%7D&sq=coin&ip=1&facetRequest=true&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F7cc62393-47e5-4a25-9f99-55c8168a601b%22%7D%7D%5D%7D)
[Specimens](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22maple%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22leaf%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=maple+leaf&ip=1&facetRequest=true&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F5f857a13-add4-4c25-ae8b-019975e75bcd%22%7D%7D%5D%7D)
[Audio](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22box%22%2C%22_lang%22%3A%22en%22%7D&sq=box&ip=1&facetRequest=true&if=%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2Fb6cb6d82-3a56-443f-8826-139c201afd2a%22%7D%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2Fb6cb6d82-3a56-443f-8826-139c201afd2a%22%7D%7D%7D%5D%7D%2C%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2Ff2da1720-9e6d-4c49-9a10-5771ff5a5c39%22%7D%7D%2C%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F1ee3a28c-d10c-4e7d-8d73-dea682a7ca28%22%7D%7D%5D%7D)
[Video](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22video%22%2C%22_lang%22%3A%22en%22%7D&sq=video&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2Facf2cace-57e0-4237-b9f9-6b6b5dc4c51c%22%7D%7D%5D%7D&facetRequest=true)
[Visual Works](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D&sq=o%27keeffe&ip=1&facetRequest=true&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F4a172143-a50e-4d91-a88b-a9931bceecf1%22%7D%7D%5D%7D)
[Clothing](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22robe%22%2C%22_lang%22%3A%22en%22%7D&sq=robe&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F9bca0cc3-3b2f-4020-ba8e-ec472cd3b03f%22%7D%7D%5D%7D&facetRequest=true)
[Journals & Newspapers](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22Washington%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22post%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=Washington+post&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F5ef5aa2a-669c-449e-8a32-5582c5f96514%22%7D%7D%2C%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F41768106-6076-482d-821b-a7d197d6adbc%22%7D%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F41768106-6076-482d-821b-a7d197d6adbc%22%7D%7D%7D%5D%7D%5D%7D&facetRequest=true)
[Furniture record](https://lux.collections.yale.edu/view/object/070f65b6-849d-4c6f-a7ff-1d4a87384f47)
[Photographs](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D&sq=o%27keeffe&ip=1&facetRequest=true&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2Ff391b71c-208e-46eb-8701-ad9cf965fd62%22%7D%7D%5D%7D)

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Heather~~
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD
- [x] Frontend requirements- TBD
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

~**UAT/LUX Examples:**~
- ~Example endpoints from LUX to use for development and testing, if applicable.~

**Dependencies/Blocks:**
- Blocking: https://github.com/project-lux/lux-frontend/issues/40
- ~Blocked by: new data set~ No longer blocked as of 4/11 

**Related Github Issues:**
- https://git.yale.edu/lux-its/lux-web/issues/1776
- https://github.com/project-lux/lux-marklogic/issues/59 (Dupe) 

**Related links:**

**Comment by ar2674** [comment]
Added all info from #59 into this ticket. @clarkepeterf @prowns

**Comment by roamye** [comment]
there will be a new data set soon where we will no longer use the data constants but instead AATs. The issue will need to be re-formatted. It will be blocked until the new data set is available.

**Comment by roamye** [comment]
No longer blocked by new data set

**Comment by roamye** [comment]
need to clarify this with @clarkepeterf.

**Comment by roamye** [comment]
Musical notation: https://lux-front-sbx.collections.yale.edu/data/object/18e97a66-9b83-46d8-a79d-9d0fa063e311

**Comment by prowns** [comment]
@clarkepeterf and @clarkepeterf - the suggestion is to close this in favor of #54 .  Can you please confirm that?

**Comment by prowns** [comment]
Ok to close per team meeting 4/18.
