### ISSUE TITLE
Order both Campus Division and Collection Facet results on Objects by number of results descending

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#57]
**Problem Description:**

This comes from https://github.com/project-lux/lux-frontend/issues/49

The Campus Division (responsibleUnits) and Collection (responsibleCollections) facets currently return in a random sort order. Sort them by count descending (most results at the top, least at the bottom)

**Expected Behavior/Solution:**
The Campus Division (responsibleUnits) and Collection (responsibleCollections) facets currently return in a random sort order. Sort them by count descending (most results at the top, least at the bottom)

**Requirements:**
No frontend or middle tier changes needed. Once fixed in ML, it will show up correctly on the frontend.

The Campus Division (responsibleUnits) and Collection (responsibleCollections) facets currently return in a random sort order. Sort them by count descending (most results at the top, least at the bottom)

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
- [ ] Questions
  - [ ] Should this wait for the decision about how we are changing the Campus Division/Collection hierarchy to include other entities? (Elizabethan Club, Paul Mellon Centre, Campus Art Collection)

**UAT/LUX Examples:**

Both Campus Division and Collections facets should be sorted by number of results at this link
https://lux-front-tst.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22blue%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22train%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=blue+train

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

~~**Related Github Issues:**~~

**Related links:**

Links:

https://www.bugherd.com/projects/284041/tasks/1772
https://lux-front-tst.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22yosemite%22%2C%22_lang%22%3A%22en%22%7D&sq=yosemite

~~**Wireframe/Mockup:**~~

**Comment by roamye** [comment]
Per UAT this is approved.

**Comment by roamye** [comment]
Looks good in prod, closing
