### ISSUE TITLE
Configuration Updates for Advanced Search 

### ISSUE THREAD

**Issue by ar2674** [project-lux/lux-marklogic#64]
**Problem Description:**
Need a ML advanced search configuration update to allow for searching objects/works that are about a given object/work. 

**Expected Behavior/Solution:**
TBD

**Requirements:**
TBD

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**
- Blocking: https://github.com/project-lux/lux-frontend/issues/29

**Related Github Issues:**
- https://github.com/project-lux/lux-marklogic/issues/74 (new ticket of this issue) 
**Related links:**

~**Wireframe/Mockup:**~
~Place wireframe/mockup for the proposed solution at end of ticket.~

**Comment by ar2674** [comment]
@clarkepeterf I am not sure how to form this ticket anymore than what I have done. Would you be able to help me form this? Thank you.

**Comment by roamye** [comment]
closing as new issue was created #74
