### ISSUE TITLE
Fix Relation Names For agent relatedToEvent - supports FE 8

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#67]
**Problem Description:**
There are no relation names for 
**Expected Behavior/Solution:**
There are new relation names for the relationships returned from agent relatedToEvent:

  'created-carriedBy-memberOf-usedForEvent': 'Created Works Carried by Objects Used At',
  'encountered-memberOf-usedForEvent': 'Encountered Objects Used At',
  'produced-memberOf-usedForEvent': 'Produced Objects Used At',
  'published-carriedBy-memberOf-usedForEvent': 'Published Works Carried by Objects Used At',
  'subjectOfAgent-carriedBy-memberOf-usedForEvent': 'Is the Subject of Works Carried by Objects Used At'

**Requirements:**
List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

Reviewable via the frontend issue: [Events: Related People and Groups (from 402)](https://github.com/project-lux/lux-frontend/issues/8)

**Dependencies/Blocks:**

- Blocking: https://github.com/project-lux/lux-middletier/issues/29
- Which also blocks: https://github.com/project-lux/lux-frontend/issues/8

**Related Github Issues:**
- https://github.com/project-lux/lux-frontend/issues/8

**Related links:**

N/A

**Wireframe/Mockup:**
N/A

**Comment by clarkepeterf** [comment]
@prowns  this is a very quick one and blocks a HAL link ticket- I'm tempted to just knock it out ASAP tomorrow, but putting in prioritization review for now

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
Looks good in prod, closing.
