### ISSUE TITLE
Update Facet Via Search Code For Responsible Units and Responsible Collections - supports FE 132, 153

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#68]
**Problem Description:**
The logic for determining Responsible Units and Responsible Collections needs to change

**Expected Behavior/Solution:**
The logic for detecting Responsible Collections should be
 - A set which is classified as a Collection, that contains the object

The logic for determining Responsible Units should be either:
- An agent that curated a set, and is not classified as a department.
- An agent whose member agent (that is a department) curated a set

**Requirements:**
N/A

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~

From ITS 4/5 Meeting Next Steps:
- [ ] Remove HAL link; current collections facet (semantics) 
- [ ] Collections becomes a normal indexed facet
- [X] Questions

From ITS 4/5 Meeting: 

The[ Elizabethan Club](https://lux-front-dev.collections.yale.edu/view/group/fd44da88-aefb-41d5-9994-ed91ce508411) is currently classified as a Department. But I think we want it to be a Unit. **Does that mean the data will change such that it is no longer classified as a Department?**
- Should be based on sets.
~~- Delete one HAL link and removes semantic facets (department)~~ - not possible because we should do a semantic search and make sure all sets are classfied as Collections (and not Archives)
- Unit: agent that curates a set or carries a department that curates a set
- Eliz Club will need to be converted to a Unit, and its department will be “Elizabethan Club Collection”
- Peter will make changes locally to test

**Does this require the new dataset is available?** 
- Yes, we will need new data that says Eliz. Club is a unit
- No front end changes needed
- Can test again new data in SBX

**UAT/LUX Examples:**
Collections Update:
The Collections facet now actually uses Collections rather than Departments.
E.g. [This search in TST](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22ouse%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22bridge%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22%2C%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22york%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=ouse+bridge%2C+york&ip=1&if=%7B%22AND%22%3A%5B%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fset%2F56dc1a97-4dfa-4a30-b028-f816575da1ab%22%7D%7D%5D%7D&facetRequest=true) where the facet is "Prints and Drawings **Collection**, Yale Center for British Art"
vs.
[This search in PRD](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22ouse%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22bridge%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22%2C%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22york%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=ouse+bridge%2C+york&ip=1&if=%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F2aaa9b33-959a-4e24-980b-b95824cde3df%22%7D%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F2aaa9b33-959a-4e24-980b-b95824cde3df%22%7D%7D%7D%5D%7D%5D%7D&facetRequest=true) where the facet is "Prints and Drawings **Department**, Yale Center for British Art"
Responsible Unit Update:
The data is not updated to show the Responsible Unit update.

**Dependencies/Blocks:**

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
- Blocking:
- [ ] Frontend ticket -  https://github.com/project-lux/lux-frontend/issues/132
- https://github.com/project-lux/lux-frontend/issues/153

**Related Github Issues:**

**Related links:**

N/A

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
labeled as normal but should still be prioritized.

**Comment by roamye** [comment]
@prowns @clarkepeterf I have added meeting notes inside this issue under "Needed for promotion".

**Comment by roamye** [comment]
@clarkepeterf can this be moved to reviewable? the UAT of the FE tix work fine in tst. (https://github.com/project-lux/lux-frontend/issues/132)

**Comment by roamye** [comment]
Looks good in prod, closing.
