### ISSUE TITLE
Add User Facing Config for Agent's recordType

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#75]
**Problem Description:**
The frontend has a facet to choose between Person or Group but there is not an equivalent field in Advanced Search

**Expected Behavior/Solution:**
There is a 'Person or Group' field in advanced search. This can be achieved by changing the generated Marklogic configuration for recordType

**Requirements:**
N/A

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- visiting this endpoint (https://lux-front-tst.collections.yale.edu/api/advanced-search-config), you should be able to search for "recordType" and see the following:
```
"recordType": {
  "label": "Person or Group",
  "helpText": "Search only records that are a Person or search only for records that are a Group",
  "relation": "text"
  },
  "allowedOptionsName": "keyword"
},
```

**Dependencies/Blocks:**

This should be deployed concurrently with https://github.com/project-lux/lux-frontend/issues/141

**Related Github Issues:**

- https://github.com/project-lux/lux-frontend/issues/141

**Related links:**

https://www.bugherd.com/projects/284041/tasks/2062

**Wireframe/Mockup:**
N/A

**Comment by clarkepeterf** [comment]
This code is ready to go, but needs frontend implementation from https://github.com/project-lux/lux-frontend/issues/141 to be functional

**Comment by clarkepeterf** [comment]
To be deployed to TST on 4/15/2023

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
'Record Type' was found in prod link so it looks good in prod. Closing.
