### ISSUE TITLE
Determine if custom error handler is still required

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-marklogic#89]
> [!NOTE]
> This ticket blocks #178.  If we decide to keep the custom error handler, we also have the choice of implementing the blocked ticket; else, the blocked ticket should be closed as not needed.

Changes between ML 11 EA and ML 11.1.0 may have made the primary purpose of the custom app server error handler ([luxErrorHandler.mjs](https://github.com/project-lux/lux-marklogic/blob/main/src/main/ml-modules/base/root/luxErrorHandler.mjs)) obsolete.  The scope of this ticket is to determine if that is true and whether it is best to revert to the default error handler.

The primary purpose of the custom error handler is to prevent timed out requests from being retried, and thus conserve cluster resources.  The generated data service proxy can retry requests multiple times when the response status code is 502, 503, or 504.*  Providing ML does not issue this status code for timed out requests, we may want to revert to the default error handler.

Recent and limited manual tests with ML 11.1.0 reflected ML returns a 500 for timed out requests.  This would go against the secondary objective of consistently return status code 408 for timed out requests.**

A second reason we may want to still try the default error handler is ML Engineering's suspicion that the custom error handler may be a contributing factor to the v8 engine failing during the scripted performance test.  Evidence is yet to back this suspicion.

If we elect to test this, it should be tested in the context of the scripted performance test.

\* Before setting up for this test, we should determine whether the generated data service proxy retry behaviors are the same in the in-use version and, if there is a later version available, whether still true there too.

\*\*  Before setting up for this test, we should think through middle tier and frontend implications of returning a 408 or 500 for timed out requests.

Per comment below: I'd like Engineering to finish their investigation of the v8 engine crash (MLE-12588) before we decide whether to keep the custom error handler or not. | https://github.com/project-lux/lux-marklogic/issues/34

**Comment by roamye** [comment]
@brent-hartwig - should @clarkepeterf be an assignee to this ticket? or just you? There is currently no one listed for this.

**Comment by brent-hartwig** [comment]
@roamye, is this being considered for development soon?  I'd like Engineering to finish their investigation of the v8 engine crash (MLE-12588) before we decide whether to keep the custom error handler or not.  Related:

* Facet pagination (#160 and #161) stabilized the system during performance tests.
* Presently day, we're only seeing a handful of 408s during performance tests.
* If we keep the custom error handler, #178 captures a scenario it could handle better.

**Comment by roamye** [comment]
@brent-hartwig - I can bring this up in UAT this thursday for review. Is there a ticket for the investigation for the V8 Engine Crash (MLE-12588)?

**Comment by brent-hartwig** [comment]
@roamye, yes, that ticket is #34, which also references MarkLogic Support ticket no. 35746.

**Comment by jffcamp** [comment]
This is not yet ready for development. It is still in 'forming' because we are waiting for the conclusion of the ML investigation linked in #34.

**Comment by brent-hartwig** [comment]
I was able to reproduce the v8 engine crash in ML 11.3.0 GA without the custom error handler.  While this does not mean the customer error handler cannot contribute to a crash, it does mean it is not the only reason.  Removing the blocked label and moving to Prioritization Review.  Note that #178 can be unblocked if we decide to keep the custom error handler.

**Comment by roamye** [comment]
@jffcamp - from Brent's message above, it seems like it is more of a preference on whether we keep it or remove it. 
Do we want to keep the custom error handler?

**Comment by jffcamp** [comment]
I believe we should keep the custom error handler.

Jeffrey Campbell
Pronouns: he/him/his

Phone: 203-432-8554
Cell: 475-201-5873

**Comment by roamye** [comment]
Since it has been decided to keep the custom handler I have moved this issue - https://github.com/project-lux/lux-marklogic/issues/178 - into backlog as it was previously blocked.

**Comment by clarkepeterf** [comment]
I think we may still want to get rid of the custom error handler, or at least modify it. It may be helpful to return HTTP 408 or 500 to reduce the number of retries in the middle tier. The middle tier setup to retry if there is a HTTP 502,503, or 504, using MarkLogics node-client-api [source here](https://github.com/marklogic/node-client-api/blob/3.3.0/lib/requester.js#L339-L343)

If we want to keep the custom error handler, this ticket can be closed, as no action is needed.

**Comment by roamye** [comment]
Should this be discussed in next weeks agenda instead?

**Comment by clarkepeterf** [comment]
@roamye I think most people in the team meeting are not involved with the error handler in a way to have much of an opinion on it

@brent-hartwig Without the custom error handler, does Marklogic Server itself return HTTP 502, 503, or 504s? Or are those coming from the AWS load balancer?

**Comment by brent-hartwig** [comment]
@clarkepeterf, in the context of the performance test, we have observed the load balancer returning many 504s when the ML app servers refused additional requests:

![image](https://github.com/user-attachments/assets/314c5961-4a8c-4eb2-8e0d-c56a6d07903c)

The above is a trimmed down version from copying from https://github.com/project-lux/lux-marklogic/issues/181#issuecomment-2182764059.

I tend to doubt ML would return 502 (bad gateway), 503 (service unavailable) or 504 (gateway timeout).

**Comment by clarkepeterf** [comment]
@brent-hartwig Ok, since ML is unlikely to return those status codes, and the primary purpose of the custom error handler was to prevent those, I would think we can get rid of the custom error handler.

Do you see any other reason to keep it?

**Comment by brent-hartwig** [comment]
@clarkepeterf, not a good enough one but let's document what else it did:

1. If the code was `XDMP-EXTIME`, the response status code was set to 408.  There were historical and possibly present-day issues with all of the timeouts going through the custom error handler.
2. If the error was `XDMP-ENDPOINTNULLABLE`, the custom error handler would identify which required parameter was missing.  This would be more helpful if the backend API was being consumed by many and we didn't have [stellar documentation](https://github.com/project-lux/lux-marklogic/blob/main/docs/lux-backend-api-usage.md) :)

I think this would be everything to remove it:

1. Delete customErrorHandler.mjs
2. Change the value of the `error-handler` property in both app server configuration files.  `"error-handler": ""` may work.  Otherwise, I believe the value is `/MarkLogic/rest-api/error-handler.xqy`.
3. Delete `TRACE_NAME_ERROR` and its export.
4. Delete the `LuxError` documentation in lux-backend-deployment.md
5. And we could close #178.

**Comment by clarkepeterf** [comment]
Ok, I think we have determined that the custom error handler is not required, which was the scope of this ticket. I created https://github.com/project-lux/lux-marklogic/issues/317 for the actual removal of the error handler
