### ISSUE TITLE
Backup auxiliary databases separate from the content databases (from 556)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-marklogic#9]
This is a follow-up to #543 and its PR https://git.yale.edu/lux-its/marklogic/pull/550 whereby we now know the lux-content database is configured to be backed up with the security and schemas databases.  The scope of this ticket is for each database that is presently covered by a backup schedule to have its own backup schedule to ensure overlapping backup jobs do not attempt to backup the same database --as MarkLogic will force one of the jobs to fail.  Additional S3 directories will need to be created.  Consider implementing #544 at the same time.

**Comment by clarkepeterf** [comment]
wondering if this is a job for @xinjianguo

**Comment by brent-hartwig** [comment]
Closing this ticket given:

* The security database has its own and better detailed ticket: #258 
* The schemas database is empty.
* The lux-content database is not configured to a triggers database.
* The above comprises a content database's auxiliary databases.
* We also have #8 for the App-Services database.
