### ISSUE TITLE
Create Concept Related To Event Related List

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-marklogic#96]
**Problem Description:**
The frontend wants a related list for concepts related to events

**Expected Behavior/Solution:**
There should be a related list that returns concepts related to events

**Requirements:**

**Needed for promotion:**

**UAT/LUX Examples:**

evidence of this issue being completed is in the MT and FE tickets:
  - MT: https://github.com/project-lux/lux-middletier/issues/51
  - FE: https://github.com/project-lux/lux-frontend/issues/180

**Dependencies/Blocks:**

- Blocking:
  - MT: https://github.com/project-lux/lux-middletier/issues/51
  - which blocks: FE: https://github.com/project-lux/lux-frontend/issues/180

**Related Github Issues:**

**Related links:**

**Wireframe/Mockup:**

**Comment by roamye** [comment]
@clarkepeterf 

I want to make sure I understand this correctly. The creation of Concept Related To Event helps with making the Related Subjects in https://github.com/project-lux/lux-frontend/issues/180 into a related list? Or is Concept Related To Event something different? 

Also will there be any UAT examples or can we use the ones from the FE 180 tix? 

Thanks,

**Comment by roamye** [comment]
UAT from FE looks good in prod, closing.
